/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { deliveryAttemptsGetDeliveryAttempt } from "../../funcs/deliveryAttemptsGetDeliveryAttempt.js";
import { GetDeliveryAttemptRequest$zodSchema } from "../../models/getdeliveryattemptop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetDeliveryAttemptRequest$zodSchema,
};

export const tool$deliveryAttemptsGetDeliveryAttempt: ToolDefinition<
  typeof args
> = {
  name: "delivery-attempts-get-delivery-attempt",
  description: `Retrieve a delivery attempt

This endpoint fetches an app event delivery attempt`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await deliveryAttemptsGetDeliveryAttempt(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
