/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsUpdateEndpoint } from "../../funcs/endpointsUpdateEndpoint.js";
import { UpdateEndpointRequest$zodSchema } from "../../models/updateendpointop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateEndpointRequest$zodSchema,
};

export const tool$endpointsUpdateEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-update-endpoint",
  description: `Update an endpoint

This endpoint updates an endpoint`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsUpdateEndpoint(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
