/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsGetEndpoints } from "../../funcs/endpointsGetEndpoints.js";
import { GetEndpointsRequest$zodSchema } from "../../models/getendpointsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEndpointsRequest$zodSchema,
};

export const tool$endpointsGetEndpoints: ToolDefinition<typeof args> = {
  name: "endpoints-get-endpoints",
  description: `List all endpoints

This endpoint fetches an endpoints`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsGetEndpoints(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
