/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsPauseEndpoint } from "../../funcs/endpointsPauseEndpoint.js";
import { PauseEndpointRequest$zodSchema } from "../../models/pauseendpointop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PauseEndpointRequest$zodSchema,
};

export const tool$endpointsPauseEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-pause-endpoint",
  description: `Pause endpoint

Toggles an endpoint's status between active and paused states`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsPauseEndpoint(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
