/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { endpointsGetEndpoints } from "../../funcs/endpointsGetEndpoints.js";
import {
  CustomerIdSpecial$zodSchema,
  Direction$zodSchema,
} from "../../models/getendpointsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  projectID: z.string().describe("Project ID"),
  direction: Direction$zodSchema.optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  ownerId: z.string().describe("The owner ID of the endpoint").optional(),
  perPage: z.number().int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  q: z.string().describe("The name of the endpoint").optional(),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
  customer_id_special: CustomerIdSpecial$zodSchema.optional(),
};

export const tool$endpointsGetEndpoints: ToolDefinition<typeof args> = {
  name: "get-all-endpoints",
  description: `List all endpoints

This endpoint fetches an endpoints`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsGetEndpoints(
      client,
      args.projectID,
      args.direction,
      args.next_page_cursor,
      args.ownerId,
      args.perPage,
      args.prev_page_cursor,
      args.q,
      args.sort,
      args.customer_id_special,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
