/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { endpointsCreateEndpoint } from "../../funcs/endpointsCreateEndpoint.js";
import { CreateEndpoint$zodSchema } from "../../models/createendpoint.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  CreateEndpoint: CreateEndpoint$zodSchema,
  projectID: z.string().describe("Project ID"),
};

export const tool$endpointsCreateEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-create-endpoint",
  description: `Create an endpoint

This endpoint creates an endpoint`,
  annotations: {
    "destructiveHint": true,
    "idempotentHint": true,
    "openWorldHint": true,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsCreateEndpoint(
      client,
      args.CreateEndpoint,
      args.projectID,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
