/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsGetEndpoint } from "../../funcs/endpointsGetEndpoint.js";
import { GetEndpointRequest$zodSchema } from "../../models/getendpointop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEndpointRequest$zodSchema,
};

export const tool$endpointsGetEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-get-endpoint",
  description: `Retrieve endpoint

This endpoint fetches an endpoint`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsGetEndpoint(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
