/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsActivateEndpoint } from "../../funcs/endpointsActivateEndpoint.js";
import { ActivateEndpointRequest$zodSchema } from "../../models/activateendpointop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ActivateEndpointRequest$zodSchema,
};

export const tool$endpointsActivateEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-activate-endpoint",
  description: `Activate endpoint

Activated an inactive endpoint`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsActivateEndpoint(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
