/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsDeleteEndpoint } from "../../funcs/endpointsDeleteEndpoint.js";
import { DeleteEndpointRequest$zodSchema } from "../../models/deleteendpointop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteEndpointRequest$zodSchema,
};

export const tool$endpointsDeleteEndpoint: ToolDefinition<typeof args> = {
  name: "endpoints-delete-endpoint",
  description: `Delete endpoint

This endpoint deletes an endpoint`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsDeleteEndpoint(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
