/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { endpointsExpireSecret } from "../../funcs/endpointsExpireSecret.js";
import { ExpireSecretRequest$zodSchema } from "../../models/expiresecretop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExpireSecretRequest$zodSchema,
};

export const tool$endpointsExpireSecret: ToolDefinition<typeof args> = {
  name: "endpoints-expire-secret",
  description: `Roll endpoint secret

This endpoint expires and re-generates the endpoint secret.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await endpointsExpireSecret(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
