/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventDeliveriesResendEventDelivery } from "../../funcs/eventDeliveriesResendEventDelivery.js";
import { ResendEventDeliveryRequest$zodSchema } from "../../models/resendeventdeliveryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ResendEventDeliveryRequest$zodSchema,
};

export const tool$eventDeliveriesResendEventDelivery: ToolDefinition<
  typeof args
> = {
  name: "event-deliveries-resend-event-delivery",
  description: `Retry event delivery

This endpoint retries an event delivery.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventDeliveriesResendEventDelivery(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
