/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetEventsPaged } from "../../funcs/eventsGetEventsPaged.js";
import { GetEventsPagedRequest$zodSchema } from "../../models/geteventspagedop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventsPagedRequest$zodSchema,
};

export const tool$eventsGetEventsPaged: ToolDefinition<typeof args> = {
  name: "events-get-events-paged",
  description: `List all events

This endpoint fetches app events with pagination`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsGetEventsPaged(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
