/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventDeliveriesForceResendEventDeliveries } from "../../funcs/eventDeliveriesForceResendEventDeliveries.js";
import { ForceResendEventDeliveriesRequest$zodSchema } from "../../models/forceresendeventdeliveriesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ForceResendEventDeliveriesRequest$zodSchema,
};

export const tool$eventDeliveriesForceResendEventDeliveries: ToolDefinition<
  typeof args
> = {
  name: "event-deliveries-force-resend-event-deliveries",
  description: `Force retry event delivery

This endpoint enables you retry a previously successful event delivery`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventDeliveriesForceResendEventDeliveries(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
