/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsReplayEndpointEvent } from "../../funcs/eventsReplayEndpointEvent.js";
import { ReplayEndpointEventRequest$zodSchema } from "../../models/replayendpointeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReplayEndpointEventRequest$zodSchema,
};

export const tool$eventsReplayEndpointEvent: ToolDefinition<typeof args> = {
  name: "events-replay-endpoint-event",
  description: `Replay event

This endpoint replays an event afresh assuming it is a new event.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsReplayEndpointEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
