/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesDeprecateEventType } from "../../funcs/eventTypesDeprecateEventType.js";
import { DeprecateEventTypeRequest$zodSchema } from "../../models/deprecateeventtypeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeprecateEventTypeRequest$zodSchema,
};

export const tool$eventTypesDeprecateEventType: ToolDefinition<typeof args> = {
  name: "event-types-deprecate-event-type",
  description: `Deprecates an event type

This endpoint deprecates an event type`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventTypesDeprecateEventType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
