/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventDeliveriesGetEventDeliveriesPaged } from "../../funcs/eventDeliveriesGetEventDeliveriesPaged.js";
import { GetEventDeliveriesPagedRequest$zodSchema } from "../../models/geteventdeliveriespagedop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventDeliveriesPagedRequest$zodSchema,
};

export const tool$eventDeliveriesGetEventDeliveriesPaged: ToolDefinition<
  typeof args
> = {
  name: "event-deliveries-get-event-deliveries-paged",
  description: `List all event deliveries

This endpoint retrieves all event deliveries paginated.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventDeliveriesGetEventDeliveriesPaged(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
