/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsCreateDynamicEvent } from "../../funcs/eventsCreateDynamicEvent.js";
import { CreateDynamicEventRequest$zodSchema } from "../../models/createdynamiceventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateDynamicEventRequest$zodSchema,
};

export const tool$eventsCreateDynamicEvent: ToolDefinition<typeof args> = {
  name: "events-create-dynamic-event",
  description: `Dynamic Events

This endpoint does not require creating endpoint and subscriptions ahead of time. Instead, you supply the endpoint and the payload, and Convoy delivers the events`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsCreateDynamicEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
