/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesGetEventTypes } from "../../funcs/eventTypesGetEventTypes.js";
import { GetEventTypesRequest$zodSchema } from "../../models/geteventtypesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventTypesRequest$zodSchema,
};

export const tool$eventTypesGetEventTypes: ToolDefinition<typeof args> = {
  name: "event-types-get-event-types",
  description: `Retrieves a project's event types

This endpoint fetches the project's event types`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventTypesGetEventTypes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
