/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsCreateEndpointEvent } from "../../funcs/eventsCreateEndpointEvent.js";
import { CreateEndpointEventRequest$zodSchema } from "../../models/createendpointeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateEndpointEventRequest$zodSchema,
};

export const tool$eventsCreateEndpointEvent: ToolDefinition<typeof args> = {
  name: "events-create-endpoint-event",
  description: `Create an event

This endpoint creates an endpoint event`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsCreateEndpointEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
