/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetEndpointEvent } from "../../funcs/eventsGetEndpointEvent.js";
import { GetEndpointEventRequest$zodSchema } from "../../models/getendpointeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEndpointEventRequest$zodSchema,
};

export const tool$eventsGetEndpointEvent: ToolDefinition<typeof args> = {
  name: "events-get-endpoint-event",
  description: `Retrieve an event

This endpoint retrieves an event`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsGetEndpointEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
