/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsCreateBroadcastEvent } from "../../funcs/eventsCreateBroadcastEvent.js";
import { CreateBroadcastEventRequest$zodSchema } from "../../models/createbroadcasteventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateBroadcastEventRequest$zodSchema,
};

export const tool$eventsCreateBroadcastEvent: ToolDefinition<typeof args> = {
  name: "events-create-broadcast-event",
  description: `Create a broadcast event

This endpoint creates a event that is broadcast to every endpoint whose subscription matches the given event type.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsCreateBroadcastEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
