/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsBatchReplayEvents } from "../../funcs/eventsBatchReplayEvents.js";
import { BatchReplayEventsRequest$zodSchema } from "../../models/batchreplayeventsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BatchReplayEventsRequest$zodSchema,
};

export const tool$eventsBatchReplayEvents: ToolDefinition<typeof args> = {
  name: "events-batch-replay-events",
  description: `Batch replay events

This endpoint replays multiple events at once.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventsBatchReplayEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
