/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesImportOpenApiSpec } from "../../funcs/eventTypesImportOpenApiSpec.js";
import { ImportOpenApiSpecRequest$zodSchema } from "../../models/importopenapispecop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ImportOpenApiSpecRequest$zodSchema,
};

export const tool$eventTypesImportOpenApiSpec: ToolDefinition<typeof args> = {
  name: "event-types-import-open-api-spec",
  description: `Import event types from OpenAPI spec

This endpoint imports event types from an OpenAPI specification`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventTypesImportOpenApiSpec(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
