/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesUpdateEventType } from "../../funcs/eventTypesUpdateEventType.js";
import { UpdateEventTypeRequest$zodSchema } from "../../models/updateeventtypeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateEventTypeRequest$zodSchema,
};

export const tool$eventTypesUpdateEventType: ToolDefinition<typeof args> = {
  name: "event-types-update-event-type",
  description: `Updates an event type

This endpoint updates an event type`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventTypesUpdateEventType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
