/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventTypesCreateEventType } from "../../funcs/eventTypesCreateEventType.js";
import { CreateEventTypeRequest$zodSchema } from "../../models/createeventtypeop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateEventTypeRequest$zodSchema,
};

export const tool$eventTypesCreateEventType: ToolDefinition<typeof args> = {
  name: "event-types-create-event-type",
  description: `Create an event type

This endpoint creates an event type`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventTypesCreateEventType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
