/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventDeliveriesBatchRetryEventDelivery } from "../../funcs/eventDeliveriesBatchRetryEventDelivery.js";
import { BatchRetryEventDeliveryRequest$zodSchema } from "../../models/batchretryeventdeliveryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BatchRetryEventDeliveryRequest$zodSchema,
};

export const tool$eventDeliveriesBatchRetryEventDelivery: ToolDefinition<
  typeof args
> = {
  name: "event-deliveries-batch-retry-event-delivery",
  description: `Batch retry event delivery

This endpoint batch retries multiple event deliveries at once.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await eventDeliveriesBatchRetryEventDelivery(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
