/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersGetFilter } from "../../funcs/filtersGetFilter.js";
import { GetFilterRequest$zodSchema } from "../../models/getfilterop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFilterRequest$zodSchema,
};

export const tool$filtersGetFilter: ToolDefinition<typeof args> = {
  name: "filters-get-filter",
  description: `Get a filter

This endpoint retrieves a single filter`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersGetFilter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
