/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersBulkCreateFilters } from "../../funcs/filtersBulkCreateFilters.js";
import { BulkCreateFiltersRequest$zodSchema } from "../../models/bulkcreatefiltersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkCreateFiltersRequest$zodSchema,
};

export const tool$filtersBulkCreateFilters: ToolDefinition<typeof args> = {
  name: "filters-bulk-create-filters",
  description: `Create multiple subscription filters

This endpoint creates multiple filters for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersBulkCreateFilters(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
