/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersTestFilter } from "../../funcs/filtersTestFilter.js";
import { TestFilterRequestRequest$zodSchema } from "../../models/testfilterop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TestFilterRequestRequest$zodSchema,
};

export const tool$filtersTestFilter: ToolDefinition<typeof args> = {
  name: "filters-test-filter",
  description: `Test a filter

This endpoint tests a filter against a payload`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersTestFilter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
