/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersGetFilters } from "../../funcs/filtersGetFilters.js";
import { GetFiltersRequest$zodSchema } from "../../models/getfiltersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFiltersRequest$zodSchema,
};

export const tool$filtersGetFilters: ToolDefinition<typeof args> = {
  name: "filters-get-filters",
  description: `List all filters

This endpoint fetches all filters for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersGetFilters(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
