/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersDeleteFilter } from "../../funcs/filtersDeleteFilter.js";
import { DeleteFilterRequest$zodSchema } from "../../models/deletefilterop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteFilterRequest$zodSchema,
};

export const tool$filtersDeleteFilter: ToolDefinition<typeof args> = {
  name: "filters-delete-filter",
  description: `Delete a filter

This endpoint deletes a filter`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersDeleteFilter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
