/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filtersBulkUpdateFilters } from "../../funcs/filtersBulkUpdateFilters.js";
import { BulkUpdateFiltersRequest$zodSchema } from "../../models/bulkupdatefiltersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkUpdateFiltersRequest$zodSchema,
};

export const tool$filtersBulkUpdateFilters: ToolDefinition<typeof args> = {
  name: "filters-bulk-update-filters",
  description: `Update multiple subscription filters

This endpoint updates multiple filters for a subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filtersBulkUpdateFilters(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
