/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metaEventsGetMetaEventsPaged } from "../../funcs/metaEventsGetMetaEventsPaged.js";
import { GetMetaEventsPagedRequest$zodSchema } from "../../models/getmetaeventspagedop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMetaEventsPagedRequest$zodSchema,
};

export const tool$metaEventsGetMetaEventsPaged: ToolDefinition<typeof args> = {
  name: "meta-events-get-meta-events-paged",
  description: `List all meta events

This endpoint fetches meta events with pagination`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metaEventsGetMetaEventsPaged(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
