/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metaEventsResendMetaEvent } from "../../funcs/metaEventsResendMetaEvent.js";
import { ResendMetaEventRequest$zodSchema } from "../../models/resendmetaeventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ResendMetaEventRequest$zodSchema,
};

export const tool$metaEventsResendMetaEvent: ToolDefinition<typeof args> = {
  name: "meta-events-resend-meta-event",
  description: `Retry meta event

This endpoint retries a meta event`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metaEventsResendMetaEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
