/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksLoadPortalLinksPaged } from "../../funcs/portalLinksLoadPortalLinksPaged.js";
import { LoadPortalLinksPagedRequest$zodSchema } from "../../models/loadportallinkspagedop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LoadPortalLinksPagedRequest$zodSchema,
};

export const tool$portalLinksLoadPortalLinksPaged: ToolDefinition<typeof args> =
  {
    name: "portal-links-load-portal-links-paged",
    description: `List all portal links

This endpoint fetches multiple portal links`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await portalLinksLoadPortalLinksPaged(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
