/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksUpdatePortalLink } from "../../funcs/portalLinksUpdatePortalLink.js";
import { UpdatePortalLinkRequest$zodSchema } from "../../models/updateportallinkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdatePortalLinkRequest$zodSchema,
};

export const tool$portalLinksUpdatePortalLink: ToolDefinition<typeof args> = {
  name: "portal-links-update-portal-link",
  description: `Update a portal link

This endpoint updates a portal link`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await portalLinksUpdatePortalLink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
