/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksRefreshPortalLinkAuthToken } from "../../funcs/portalLinksRefreshPortalLinkAuthToken.js";
import { RefreshPortalLinkAuthTokenRequest$zodSchema } from "../../models/refreshportallinkauthtokenop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RefreshPortalLinkAuthTokenRequest$zodSchema,
};

export const tool$portalLinksRefreshPortalLinkAuthToken: ToolDefinition<
  typeof args
> = {
  name: "portal-links-refresh-portal-link-auth-token",
  description: `Get a portal link auth token

This endpoint retrieves a portal link auth token`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await portalLinksRefreshPortalLinkAuthToken(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
