/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksRevokePortalLink } from "../../funcs/portalLinksRevokePortalLink.js";
import { RevokePortalLinkRequest$zodSchema } from "../../models/revokeportallinkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RevokePortalLinkRequest$zodSchema,
};

export const tool$portalLinksRevokePortalLink: ToolDefinition<typeof args> = {
  name: "portal-links-revoke-portal-link",
  description: `Revoke a portal link

This endpoint revokes a portal link`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await portalLinksRevokePortalLink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
