/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksGeneratePortalToken } from "../../funcs/portalLinksGeneratePortalToken.js";
import { GeneratePortalTokenRequest$zodSchema } from "../../models/generateportaltokenop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GeneratePortalTokenRequest$zodSchema,
};

export const tool$portalLinksGeneratePortalToken: ToolDefinition<typeof args> =
  {
    name: "portal-links-generate-portal-token",
    description: `Updates a portal link auth token

This endpoint retrieves a portal link by its id.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await portalLinksGeneratePortalToken(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
