/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksCreatePortalLink } from "../../funcs/portalLinksCreatePortalLink.js";
import { CreatePortalLinkRequest$zodSchema } from "../../models/createportallinkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreatePortalLinkRequest$zodSchema,
};

export const tool$portalLinksCreatePortalLink: ToolDefinition<typeof args> = {
  name: "portal-links-create-portal-link",
  description: `Create a portal link

This endpoint creates a portal link`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await portalLinksCreatePortalLink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
