/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { portalLinksGetPortalLink } from "../../funcs/portalLinksGetPortalLink.js";
import { GetPortalLinkRequest$zodSchema } from "../../models/getportallinkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPortalLinkRequest$zodSchema,
};

export const tool$portalLinksGetPortalLink: ToolDefinition<typeof args> = {
  name: "portal-links-get-portal-link",
  description: `Retrieve a portal link

This endpoint retrieves a portal link by its id.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await portalLinksGetPortalLink(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
