/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesUpdateSource } from "../../funcs/sourcesUpdateSource.js";
import { UpdateSourceRequest$zodSchema } from "../../models/updatesourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateSourceRequest$zodSchema,
};

export const tool$sourcesUpdateSource: ToolDefinition<typeof args> = {
  name: "sources-update-source",
  description: `Update a source

This endpoint updates a source`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesUpdateSource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
