/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesGetSource } from "../../funcs/sourcesGetSource.js";
import { GetSourceRequest$zodSchema } from "../../models/getsourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSourceRequest$zodSchema,
};

export const tool$sourcesGetSource: ToolDefinition<typeof args> = {
  name: "sources-get-source",
  description: `Retrieve a source

This endpoint retrieves a source by its id`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesGetSource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
