/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesDeleteSource } from "../../funcs/sourcesDeleteSource.js";
import { DeleteSourceRequest$zodSchema } from "../../models/deletesourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSourceRequest$zodSchema,
};

export const tool$sourcesDeleteSource: ToolDefinition<typeof args> = {
  name: "sources-delete-source",
  description: `Delete a source

This endpoint deletes a source`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesDeleteSource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
