/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesTestSourceFunction } from "../../funcs/sourcesTestSourceFunction.js";
import { TestSourceFunctionRequest$zodSchema } from "../../models/testsourcefunctionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TestSourceFunctionRequest$zodSchema,
};

export const tool$sourcesTestSourceFunction: ToolDefinition<typeof args> = {
  name: "sources-test-source-function",
  description: `Validate source function

This endpoint validates that a filter will match a certain payload structure.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesTestSourceFunction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
