/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesCreateSource } from "../../funcs/sourcesCreateSource.js";
import { CreateSourceRequest$zodSchema } from "../../models/createsourceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateSourceRequest$zodSchema,
};

export const tool$sourcesCreateSource: ToolDefinition<typeof args> = {
  name: "sources-create-source",
  description: `Create a source

This endpoint creates a source`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesCreateSource(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
