/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sourcesLoadSourcesPaged } from "../../funcs/sourcesLoadSourcesPaged.js";
import { LoadSourcesPagedRequest$zodSchema } from "../../models/loadsourcespagedop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: LoadSourcesPagedRequest$zodSchema,
};

export const tool$sourcesLoadSourcesPaged: ToolDefinition<typeof args> = {
  name: "sources-load-sources-paged",
  description: `List all sources

This endpoint fetches multiple sources`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sourcesLoadSourcesPaged(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
