/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCreateSubscription } from "../../funcs/subscriptionsCreateSubscription.js";
import { CreateSubscriptionRequest$zodSchema } from "../../models/createsubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsCreateSubscription: ToolDefinition<typeof args> =
  {
    name: "subscriptions-create-subscription",
    description: `Create a subscription

This endpoint creates a subscriptions`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await subscriptionsCreateSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
