/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsTestSubscriptionFilter } from "../../funcs/subscriptionsTestSubscriptionFilter.js";
import { TestSubscriptionFilterRequest$zodSchema } from "../../models/testsubscriptionfilterop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TestSubscriptionFilterRequest$zodSchema,
};

export const tool$subscriptionsTestSubscriptionFilter: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-test-subscription-filter",
  description: `Validate subscription filter

This endpoint validates that a filter will match a certain payload structure.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsTestSubscriptionFilter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
