/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscription } from "../../funcs/subscriptionsGetSubscription.js";
import { GetSubscriptionRequest$zodSchema } from "../../models/getsubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsGetSubscription: ToolDefinition<typeof args> = {
  name: "subscriptions-get-subscription",
  description: `Retrieve a subscription

This endpoint retrieves a single subscription`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsGetSubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
