/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptions } from "../../funcs/subscriptionsGetSubscriptions.js";
import { GetSubscriptionsRequest$zodSchema } from "../../models/getsubscriptionsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionsRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptions: ToolDefinition<typeof args> = {
  name: "subscriptions-get-subscriptions",
  description: `List all subscriptions

This endpoint fetches all the subscriptions`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsGetSubscriptions(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
