/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsDeleteSubscription } from "../../funcs/subscriptionsDeleteSubscription.js";
import { DeleteSubscriptionRequest$zodSchema } from "../../models/deletesubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsDeleteSubscription: ToolDefinition<typeof args> =
  {
    name: "subscriptions-delete-subscription",
    description: `Delete subscription

This endpoint deletes a subscription`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await subscriptionsDeleteSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
