/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsTestSubscriptionFunction } from "../../funcs/subscriptionsTestSubscriptionFunction.js";
import { TestSubscriptionFunctionRequest$zodSchema } from "../../models/testsubscriptionfunctionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TestSubscriptionFunctionRequest$zodSchema,
};

export const tool$subscriptionsTestSubscriptionFunction: ToolDefinition<
  typeof args
> = {
  name: "subscriptions-test-subscription-function",
  description: `Test a subscription function

This endpoint test runs a transform function against a payload.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await subscriptionsTestSubscriptionFunction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
