/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsUpdateSubscription } from "../../funcs/subscriptionsUpdateSubscription.js";
import { UpdateSubscriptionRequest$zodSchema } from "../../models/updatesubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsUpdateSubscription: ToolDefinition<typeof args> =
  {
    name: "subscriptions-update-subscription",
    description: `Update a subscription

This endpoint updates a subscription`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await subscriptionsUpdateSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
