/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SDKCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import { CreateEndpoint } from "../models/createendpoint.js";
import {
  CreateEndpointRequest,
  CreateEndpointRequest$zodSchema,
  CreateEndpointResponse,
  CreateEndpointResponse$zodSchema,
} from "../models/createendpointop.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Create an endpoint
 *
 * @remarks
 * This endpoint creates an endpoint
 */
export function endpointsCreateEndpoint(
  client$: SDKCore,
  CreateEndpoint: CreateEndpoint,
  projectID: string,
  options?: RequestOptions,
): APIPromise<
  Result<
    CreateEndpointResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    CreateEndpoint,
    projectID,
    options,
  ));
}

async function $do(
  client$: SDKCore,
  CreateEndpoint: CreateEndpoint,
  projectID: string,
  options?: RequestOptions,
): Promise<
  [
    Result<
      CreateEndpointResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const input$: CreateEndpointRequest = {
    CreateEndpoint: CreateEndpoint,
    projectID: projectID,
  };

  const parsed$ = safeParse(
    input$,
    (value$) => CreateEndpointRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON("body", payload$.CreateEndpoint, { explode: true });

  const pathParams$ = {
    projectID: encodeSimple("projectID", payload$.projectID, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/v1/projects/{projectID}/endpoints")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));
  const securityInput = await extractSecurity(client$._options.security);
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "CreateEndpoint",
    oAuth2Scopes: [],
    resolvedSecurity: requestSecurity,
    securitySource: client$._options.security,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    CreateEndpointResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, CreateEndpointResponse$zodSchema, {
      key: "twoHundredAndOneApplicationJsonObject",
    }),
    M.json(400, CreateEndpointResponse$zodSchema, {
      key: "fourHundredApplicationJsonObject",
    }),
    M.json(401, CreateEndpointResponse$zodSchema, {
      key: "fourHundredAndOneApplicationJsonObject",
    }),
    M.json(404, CreateEndpointResponse$zodSchema, {
      key: "fourHundredAndFourApplicationJsonObject",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
