/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ActivateEndpointRequest = { projectID: string; endpointID: string };

export const ActivateEndpointRequest$zodSchema: z.ZodType<
  ActivateEndpointRequest
> = z.object({
  endpointID: z.string().describe("Endpoint ID"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type ActivateEndpointNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ActivateEndpointNotFoundResponseBody$zodSchema: z.ZodType<
  ActivateEndpointNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type ActivateEndpointUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ActivateEndpointUnauthorizedResponseBody$zodSchema: z.ZodType<
  ActivateEndpointUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type ActivateEndpointBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ActivateEndpointBadRequestResponseBody$zodSchema: z.ZodType<
  ActivateEndpointBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Accepted
 */
export type ActivateEndpointResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EndpointResponse | undefined;
};

export const ActivateEndpointResponseBody$zodSchema: z.ZodType<
  ActivateEndpointResponseBody
> = z.object({
  data: EndpointResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Accepted");

export type ActivateEndpointResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndTwoApplicationJsonObject?:
    | ActivateEndpointResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | ActivateEndpointBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ActivateEndpointUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ActivateEndpointNotFoundResponseBody
    | undefined;
};

export const ActivateEndpointResponse$zodSchema: z.ZodType<
  ActivateEndpointResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    ActivateEndpointNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ActivateEndpointUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    ActivateEndpointBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredAndTwoApplicationJsonObject: z.lazy(() =>
    ActivateEndpointResponseBody$zodSchema
  ).optional(),
});
