/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AlertConfiguration = {
  count?: number | undefined;
  threshold?: string | undefined;
};

export const AlertConfiguration$zodSchema: z.ZodType<AlertConfiguration> = z
  .object({
    count: z.int().optional(),
    threshold: z.string().optional(),
  });
