/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmqpAuth, AmqpAuth$zodSchema } from "./amqpauth.js";
import { AmqpExchange, AmqpExchange$zodSchema } from "./amqpexchange.js";

export type AmqpPubSubconfig = {
  auth?: AmqpAuth | undefined;
  bindExchange?: AmqpExchange | undefined;
  deadLetterExchange?: string | undefined;
  host?: string | undefined;
  port?: string | undefined;
  queue?: string | undefined;
  schema?: string | undefined;
  vhost?: string | undefined;
};

export const AmqpPubSubconfig$zodSchema: z.ZodType<AmqpPubSubconfig> = z.object(
  {
    auth: AmqpAuth$zodSchema.optional(),
    bindExchange: AmqpExchange$zodSchema.optional(),
    deadLetterExchange: z.string().optional(),
    host: z.string().optional(),
    port: z.string().optional(),
    queue: z.string().optional(),
    schema: z.string().optional(),
    vhost: z.string().optional(),
  },
);
