/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AmqpExchange = {
  exchange?: string | undefined;
  routingKey?: string | undefined;
};

export const AmqpExchange$zodSchema: z.ZodType<AmqpExchange> = z.object({
  exchange: z.string().optional(),
  routingKey: z.string().optional(),
});
