/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiKey = {
  header_name?: string | undefined;
  header_value?: string | undefined;
};

export const ApiKey$zodSchema: z.ZodType<ApiKey, z.ZodTypeDef, unknown> = z
  .object({
    header_name: z.string().optional(),
    header_value: z.string().optional(),
  });
