/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ApiKey = { header_name: string; header_value: string };

export const ApiKey$zodSchema: z.ZodType<ApiKey> = z.object({
  header_name: z.string(),
  header_value: z.string(),
});
