/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BasicAuth = { password: string; username: string };

export const BasicAuth$zodSchema: z.ZodType<BasicAuth> = z.object({
  password: z.string(),
  username: z.string(),
});
