/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export const BatchReplayEventsDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type BatchReplayEventsDirection = ClosedEnum<
  typeof BatchReplayEventsDirection
>;

export const BatchReplayEventsDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type BatchReplayEventsRequest = {
  projectID: string;
  direction?: BatchReplayEventsDirection | undefined;
  endDate?: string | undefined;
  endpointId?: Array<string> | undefined;
  idempotencyKey?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  query?: string | undefined;
  sort?: string | undefined;
  sourceId?: Array<string> | undefined;
  startDate?: string | undefined;
};

export const BatchReplayEventsRequest$zodSchema: z.ZodType<
  BatchReplayEventsRequest
> = z.object({
  direction: BatchReplayEventsDirection$zodSchema.optional(),
  endDate: z.string().describe("The end date").optional(),
  endpointId: z.array(z.string()).describe(
    "A list of endpoint ids to filter by",
  ).optional(),
  idempotencyKey: z.string().describe("IdempotencyKey to filter by").optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  perPage: z.int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  query: z.string().describe("Any arbitrary value to filter the events payload")
    .optional(),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
  sourceId: z.array(z.string()).describe(
    "A list of Source IDs to filter the events by.",
  ).optional(),
  startDate: z.string().describe("The start date").optional(),
});

/**
 * Not Found
 */
export type BatchReplayEventsNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BatchReplayEventsNotFoundResponseBody$zodSchema: z.ZodType<
  BatchReplayEventsNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type BatchReplayEventsUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BatchReplayEventsUnauthorizedResponseBody$zodSchema: z.ZodType<
  BatchReplayEventsUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type BatchReplayEventsBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BatchReplayEventsBadRequestResponseBody$zodSchema: z.ZodType<
  BatchReplayEventsBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type BatchReplayEventsResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: string | undefined;
};

export const BatchReplayEventsResponseBody$zodSchema: z.ZodType<
  BatchReplayEventsResponseBody
> = z.object({
  data: z.string().optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type BatchReplayEventsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: BatchReplayEventsResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | BatchReplayEventsBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | BatchReplayEventsUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | BatchReplayEventsNotFoundResponseBody
    | undefined;
};

export const BatchReplayEventsResponse$zodSchema: z.ZodType<
  BatchReplayEventsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    BatchReplayEventsNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    BatchReplayEventsUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    BatchReplayEventsBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    BatchReplayEventsResponseBody$zodSchema
  ).optional().describe("OK"),
});
