/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Data is an arbitrary JSON value that gets sent as the body of the
 *
 * @remarks
 * webhook to the endpoints
 */
export type BroadcastEventData = {};

export const BroadcastEventData$zodSchema: z.ZodType<BroadcastEventData> = z
  .object({}).describe(
    "Data is an arbitrary JSON value that gets sent as the body of the\n"
      + "webhook to the endpoints",
  );

export type BroadcastEvent = {
  acknowledged_at?: string | undefined;
  custom_headers?: { [k: string]: string } | undefined;
  data?: BroadcastEventData | undefined;
  event_type?: string | undefined;
  idempotency_key?: string | undefined;
};

export const BroadcastEvent$zodSchema: z.ZodType<BroadcastEvent> = z.object({
  acknowledged_at: z.string().optional(),
  custom_headers: z.record(z.string(), z.string()).optional(),
  data: z.lazy(() => BroadcastEventData$zodSchema).optional(),
  event_type: z.string().optional(),
  idempotency_key: z.string().optional(),
});
