/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type BulkUpdateFilterRequest = {
  body?: { [k: string]: any } | undefined;
  event_type?: string | undefined;
  headers?: { [k: string]: any } | undefined;
  uid: string;
};

export const BulkUpdateFilterRequest$zodSchema: z.ZodType<
  BulkUpdateFilterRequest
> = z.object({
  body: z.record(z.string(), z.any()).optional(),
  event_type: z.string().optional(),
  headers: z.record(z.string(), z.any()).optional(),
  uid: z.string(),
});
