/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BulkUpdateFilterRequest,
  BulkUpdateFilterRequest$zodSchema,
} from "./bulkupdatefilterrequest.js";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type BulkUpdateFiltersRequest = {
  projectID: string;
  subscriptionID: string;
  RequestBody: Array<BulkUpdateFilterRequest>;
};

export const BulkUpdateFiltersRequest$zodSchema: z.ZodType<
  BulkUpdateFiltersRequest
> = z.object({
  RequestBody: z.array(BulkUpdateFilterRequest$zodSchema).describe(
    "Filters to update",
  ),
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("Subscription ID"),
});

/**
 * Not Found
 */
export type BulkUpdateFiltersNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkUpdateFiltersNotFoundResponseBody$zodSchema: z.ZodType<
  BulkUpdateFiltersNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type BulkUpdateFiltersUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkUpdateFiltersUnauthorizedResponseBody$zodSchema: z.ZodType<
  BulkUpdateFiltersUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type BulkUpdateFiltersBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkUpdateFiltersBadRequestResponseBody$zodSchema: z.ZodType<
  BulkUpdateFiltersBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type BulkUpdateFiltersResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<FilterResponse> | undefined;
};

export const BulkUpdateFiltersResponseBody$zodSchema: z.ZodType<
  BulkUpdateFiltersResponseBody
> = z.object({
  data: z.array(FilterResponse$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type BulkUpdateFiltersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: BulkUpdateFiltersResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | BulkUpdateFiltersBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | BulkUpdateFiltersUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | BulkUpdateFiltersNotFoundResponseBody
    | undefined;
};

export const BulkUpdateFiltersResponse$zodSchema: z.ZodType<
  BulkUpdateFiltersResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    BulkUpdateFiltersNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    BulkUpdateFiltersUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    BulkUpdateFiltersBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    BulkUpdateFiltersResponseBody$zodSchema
  ).optional().describe("OK"),
});
