/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateFilterRequest,
  CreateFilterRequest$zodSchema,
} from "./createfilterrequest.js";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type BulkCreateFiltersRequest = {
  projectID: string;
  subscriptionID: string;
  RequestBody: Array<CreateFilterRequest>;
};

export const BulkCreateFiltersRequest$zodSchema: z.ZodType<
  BulkCreateFiltersRequest
> = z.object({
  RequestBody: z.array(CreateFilterRequest$zodSchema).describe(
    "Filters to create",
  ),
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("Subscription ID"),
});

/**
 * Not Found
 */
export type BulkCreateFiltersNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkCreateFiltersNotFoundResponseBody$zodSchema: z.ZodType<
  BulkCreateFiltersNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type BulkCreateFiltersUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkCreateFiltersUnauthorizedResponseBody$zodSchema: z.ZodType<
  BulkCreateFiltersUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type BulkCreateFiltersBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const BulkCreateFiltersBadRequestResponseBody$zodSchema: z.ZodType<
  BulkCreateFiltersBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type BulkCreateFiltersResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<FilterResponse> | undefined;
};

export const BulkCreateFiltersResponseBody$zodSchema: z.ZodType<
  BulkCreateFiltersResponseBody
> = z.object({
  data: z.array(FilterResponse$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type BulkCreateFiltersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | BulkCreateFiltersResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | BulkCreateFiltersBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | BulkCreateFiltersUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | BulkCreateFiltersNotFoundResponseBody
    | undefined;
};

export const BulkCreateFiltersResponse$zodSchema: z.ZodType<
  BulkCreateFiltersResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    BulkCreateFiltersNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    BulkCreateFiltersUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    BulkCreateFiltersBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    BulkCreateFiltersResponseBody$zodSchema
  ).optional().describe("Created"),
});
