/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PortalLink, PortalLink$zodSchema } from "./portallink.js";
import {
  PortalLinkResponse,
  PortalLinkResponse$zodSchema,
} from "./portallinkresponse.js";

export type CreatePortalLinkRequest = {
  projectID: string;
  PortalLink: PortalLink;
};

export const CreatePortalLinkRequest$zodSchema: z.ZodType<
  CreatePortalLinkRequest
> = z.object({
  PortalLink: PortalLink$zodSchema,
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreatePortalLinkNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreatePortalLinkNotFoundResponseBody$zodSchema: z.ZodType<
  CreatePortalLinkNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreatePortalLinkUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreatePortalLinkUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreatePortalLinkUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreatePortalLinkBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreatePortalLinkBadRequestResponseBody$zodSchema: z.ZodType<
  CreatePortalLinkBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreatePortalLinkResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: PortalLinkResponse | undefined;
};

export const CreatePortalLinkResponseBody$zodSchema: z.ZodType<
  CreatePortalLinkResponseBody
> = z.object({
  data: PortalLinkResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreatePortalLinkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreatePortalLinkResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreatePortalLinkBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreatePortalLinkUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreatePortalLinkNotFoundResponseBody
    | undefined;
};

export const CreatePortalLinkResponse$zodSchema: z.ZodType<
  CreatePortalLinkResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreatePortalLinkNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreatePortalLinkUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreatePortalLinkBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreatePortalLinkResponseBody$zodSchema
  ).optional(),
});
