/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Data is an arbitrary JSON value that gets sent as the body of the
 *
 * @remarks
 * webhook to the endpoints
 */
export type CreateEventData = {};

export const CreateEventData$zodSchema: z.ZodType<CreateEventData> = z.object(
  {},
).describe(
  "Data is an arbitrary JSON value that gets sent as the body of the\nwebhook to the endpoints",
);

export type CreateEvent = {
  app_id?: string | undefined;
  custom_headers?: { [k: string]: string } | undefined;
  data?: CreateEventData | undefined;
  endpoint_id?: string | undefined;
  event_type?: string | undefined;
  idempotency_key?: string | undefined;
};

export const CreateEvent$zodSchema: z.ZodType<CreateEvent> = z.object({
  app_id: z.string().optional().describe(
    "Deprecated but necessary for backward compatibility.",
  ),
  custom_headers: z.record(z.string(), z.string()).optional().describe(
    "Specifies custom headers you want convoy to add when the event is dispatched to your endpoint",
  ),
  data: z.lazy(() => CreateEventData$zodSchema).optional().describe(
    "Data is an arbitrary JSON value that gets sent as the body of the\nwebhook to the endpoints",
  ),
  endpoint_id: z.string().optional().describe(
    "Specifies the endpoint to send this event to.",
  ),
  event_type: z.string().optional().describe(
    "Event Type is used for filtering and debugging e.g invoice.paid",
  ),
  idempotency_key: z.string().optional().describe(
    "Specify a key for event deduplication",
  ),
});
