/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FanoutEvent, FanoutEvent$zodSchema } from "./fanoutevent.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateEndpointFanoutEventRequest = {
  projectID: string;
  FanoutEvent: FanoutEvent;
};

export const CreateEndpointFanoutEventRequest$zodSchema: z.ZodType<
  CreateEndpointFanoutEventRequest
> = z.object({
  FanoutEvent: FanoutEvent$zodSchema.describe("Event Details"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreateEndpointFanoutEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointFanoutEventNotFoundResponseBody$zodSchema: z.ZodType<
  CreateEndpointFanoutEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateEndpointFanoutEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointFanoutEventUnauthorizedResponseBody$zodSchema:
  z.ZodType<CreateEndpointFanoutEventUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateEndpointFanoutEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointFanoutEventBadRequestResponseBody$zodSchema:
  z.ZodType<CreateEndpointFanoutEventBadRequestResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Bad Request");

/**
 * Created
 */
export type CreateEndpointFanoutEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointFanoutEventResponseBody$zodSchema: z.ZodType<
  CreateEndpointFanoutEventResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateEndpointFanoutEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreateEndpointFanoutEventResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreateEndpointFanoutEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateEndpointFanoutEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateEndpointFanoutEventNotFoundResponseBody
    | undefined;
};

export const CreateEndpointFanoutEventResponse$zodSchema: z.ZodType<
  CreateEndpointFanoutEventResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateEndpointFanoutEventNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointFanoutEventUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateEndpointFanoutEventBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointFanoutEventResponseBody$zodSchema
  ).optional().describe("Created"),
});
