/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DynamicEvent, DynamicEvent$zodSchema } from "./dynamicevent.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateDynamicEventRequest = {
  projectID: string;
  DynamicEvent: DynamicEvent;
};

export const CreateDynamicEventRequest$zodSchema: z.ZodType<
  CreateDynamicEventRequest
> = z.object({
  DynamicEvent: DynamicEvent$zodSchema.describe("Event Details"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreateDynamicEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateDynamicEventNotFoundResponseBody$zodSchema: z.ZodType<
  CreateDynamicEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateDynamicEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateDynamicEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateDynamicEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateDynamicEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateDynamicEventBadRequestResponseBody$zodSchema: z.ZodType<
  CreateDynamicEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type CreateDynamicEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  ObjectT?: ObjectT | undefined;
  fourHundredApplicationJsonObject?:
    | CreateDynamicEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateDynamicEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateDynamicEventNotFoundResponseBody
    | undefined;
};

export const CreateDynamicEventResponse$zodSchema: z.ZodType<
  CreateDynamicEventResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  ObjectT: ObjectT$zodSchema.optional().describe("Created"),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateDynamicEventNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateDynamicEventUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateDynamicEventBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
});
