/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  AlertConfiguration,
  AlertConfiguration$zodSchema,
} from "./alertconfiguration.js";
import {
  FilterConfiguration,
  FilterConfiguration$zodSchema,
} from "./filterconfiguration.js";
import {
  RateLimitConfiguration,
  RateLimitConfiguration$zodSchema,
} from "./ratelimitconfiguration.js";

/**
 * Delivery mode configuration
 */
export const CreateSubscriptionDeliveryMode = {
  AtLeastOnce: "at_least_once",
  AtMostOnce: "at_most_once",
} as const;
/**
 * Delivery mode configuration
 */
export type CreateSubscriptionDeliveryMode = OpenEnum<
  typeof CreateSubscriptionDeliveryMode
>;

export const CreateSubscriptionDeliveryMode$zodSchema = z.union([
  z.enum([
    "at_least_once",
    "at_most_once",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Delivery mode configuration");

export type CreateSubscription = {
  alert_config?: AlertConfiguration | undefined;
  app_id?: string | undefined;
  delivery_mode?: CreateSubscriptionDeliveryMode | undefined;
  endpoint_id?: string | undefined;
  filter_config?: FilterConfiguration | undefined;
  function?: string | undefined;
  name?: string | undefined;
  rate_limit_config?: RateLimitConfiguration | undefined;
  source_id?: string | undefined;
};

export const CreateSubscription$zodSchema: z.ZodType<CreateSubscription> = z
  .object({
    alert_config: AlertConfiguration$zodSchema.optional().describe(
      "Alert configuration",
    ),
    app_id: z.string().optional().describe(
      "Deprecated but necessary for backward compatibility",
    ),
    delivery_mode: CreateSubscriptionDeliveryMode$zodSchema.optional().describe(
      "Delivery mode configuration",
    ),
    endpoint_id: z.string().optional().describe("Destination endpoint ID"),
    filter_config: FilterConfiguration$zodSchema.optional().describe(
      "Filter configuration",
    ),
    function: z.string().optional().describe(
      "Convoy supports mutating your request payload using a js function. Use this field\nto specify a `transform` function for this purpose. See this[https://docs.getconvoy.io/product-manual/subscriptions#functions] for more",
    ),
    name: z.string().optional().describe("Subscription Nme"),
    rate_limit_config: RateLimitConfiguration$zodSchema.optional().describe(
      "Rate limit configuration",
    ),
    source_id: z.string().optional().describe("Source Id"),
  });
