/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Data is an arbitrary JSON value that gets sent as the body of the
 *
 * @remarks
 * webhook to the endpoints
 */
export type CreateEventData = {};

export const CreateEventData$zodSchema: z.ZodType<CreateEventData> = z.object(
  {},
).describe(
  "Data is an arbitrary JSON value that gets sent as the body of the\n"
    + "webhook to the endpoints",
);

export type CreateEvent = {
  app_id?: string | undefined;
  custom_headers?: { [k: string]: string } | undefined;
  data?: CreateEventData | undefined;
  endpoint_id?: string | undefined;
  event_type?: string | undefined;
  idempotency_key?: string | undefined;
};

export const CreateEvent$zodSchema: z.ZodType<CreateEvent> = z.object({
  app_id: z.string().optional(),
  custom_headers: z.record(z.string(), z.string()).optional(),
  data: z.lazy(() => CreateEventData$zodSchema).optional(),
  endpoint_id: z.string().optional(),
  event_type: z.string().optional(),
  idempotency_key: z.string().optional(),
});
