/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CreateEndpoint, CreateEndpoint$zodSchema } from "./createendpoint.js";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateEndpointRequest = {
  projectID: string;
  CreateEndpoint: CreateEndpoint;
};

export const CreateEndpointRequest$zodSchema: z.ZodType<CreateEndpointRequest> =
  z.object({
    CreateEndpoint: CreateEndpoint$zodSchema.describe("Endpoint Details"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type CreateEndpointNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointNotFoundResponseBody$zodSchema: z.ZodType<
  CreateEndpointNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateEndpointUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateEndpointUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateEndpointBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointBadRequestResponseBody$zodSchema: z.ZodType<
  CreateEndpointBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreateEndpointResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EndpointResponse | undefined;
};

export const CreateEndpointResponseBody$zodSchema: z.ZodType<
  CreateEndpointResponseBody
> = z.object({
  data: EndpointResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateEndpointResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreateEndpointResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreateEndpointBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateEndpointUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateEndpointNotFoundResponseBody
    | undefined;
};

export const CreateEndpointResponse$zodSchema: z.ZodType<
  CreateEndpointResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateEndpointNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateEndpointBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointResponseBody$zodSchema
  ).optional().describe("Created"),
});
