/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateSubscription,
  CreateSubscription$zodSchema,
} from "./createsubscription.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type CreateSubscriptionRequest = {
  projectID: string;
  CreateSubscription: CreateSubscription;
};

export const CreateSubscriptionRequest$zodSchema: z.ZodType<
  CreateSubscriptionRequest
> = z.object({
  CreateSubscription: CreateSubscription$zodSchema.describe(
    "Subscription details",
  ),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreateSubscriptionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateSubscriptionNotFoundResponseBody$zodSchema: z.ZodType<
  CreateSubscriptionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateSubscriptionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateSubscriptionUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateSubscriptionUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateSubscriptionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateSubscriptionBadRequestResponseBody$zodSchema: z.ZodType<
  CreateSubscriptionBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreateSubscriptionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: SubscriptionResponse | undefined;
};

export const CreateSubscriptionResponseBody$zodSchema: z.ZodType<
  CreateSubscriptionResponseBody
> = z.object({
  data: SubscriptionResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateSubscriptionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreateSubscriptionResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreateSubscriptionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateSubscriptionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateSubscriptionNotFoundResponseBody
    | undefined;
};

export const CreateSubscriptionResponse$zodSchema: z.ZodType<
  CreateSubscriptionResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateSubscriptionNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateSubscriptionUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateSubscriptionBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateSubscriptionResponseBody$zodSchema
  ).optional().describe("Created"),
});
