/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateEventType = {
  category?: string | undefined;
  description?: string | undefined;
  json_schema?: { [k: string]: any } | undefined;
  name?: string | undefined;
};

export const CreateEventType$zodSchema: z.ZodType<CreateEventType> = z.object({
  category: z.string().optional(),
  description: z.string().optional(),
  json_schema: z.record(z.string(), z.any()).optional(),
  name: z.string().optional(),
});
