/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateFilterRequest,
  CreateFilterRequest$zodSchema,
} from "./createfilterrequest.js";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateFilterRequestRequest = {
  projectID: string;
  subscriptionID: string;
  CreateFilterRequest: CreateFilterRequest;
};

export const CreateFilterRequestRequest$zodSchema: z.ZodType<
  CreateFilterRequestRequest
> = z.object({
  CreateFilterRequest: CreateFilterRequest$zodSchema.describe(
    "Filter to create",
  ),
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("Subscription ID"),
});

/**
 * Not Found
 */
export type CreateFilterNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateFilterNotFoundResponseBody$zodSchema: z.ZodType<
  CreateFilterNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateFilterUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateFilterUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateFilterUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateFilterBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateFilterBadRequestResponseBody$zodSchema: z.ZodType<
  CreateFilterBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreateFilterResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: FilterResponse | undefined;
};

export const CreateFilterResponseBody$zodSchema: z.ZodType<
  CreateFilterResponseBody
> = z.object({
  data: FilterResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateFilterResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?: CreateFilterResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | CreateFilterBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateFilterUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateFilterNotFoundResponseBody
    | undefined;
};

export const CreateFilterResponse$zodSchema: z.ZodType<CreateFilterResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      CreateFilterNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      CreateFilterUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      CreateFilterBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredAndOneApplicationJsonObject: z.lazy(() =>
      CreateFilterResponseBody$zodSchema
    ).optional().describe("Created"),
  });
