/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateEventType,
  CreateEventType$zodSchema,
} from "./createeventtype.js";
import {
  EventTypeResponse,
  EventTypeResponse$zodSchema,
} from "./eventtyperesponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateEventTypeRequest = {
  projectID: string;
  CreateEventType: CreateEventType;
};

export const CreateEventTypeRequest$zodSchema: z.ZodType<
  CreateEventTypeRequest
> = z.object({
  CreateEventType: CreateEventType$zodSchema.describe("Event Type Details"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreateEventTypeNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEventTypeNotFoundResponseBody$zodSchema: z.ZodType<
  CreateEventTypeNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateEventTypeUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEventTypeUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateEventTypeUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateEventTypeBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEventTypeBadRequestResponseBody$zodSchema: z.ZodType<
  CreateEventTypeBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreateEventTypeResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EventTypeResponse | undefined;
};

export const CreateEventTypeResponseBody$zodSchema: z.ZodType<
  CreateEventTypeResponseBody
> = z.object({
  data: EventTypeResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateEventTypeResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreateEventTypeResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreateEventTypeBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateEventTypeUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateEventTypeNotFoundResponseBody
    | undefined;
};

export const CreateEventTypeResponse$zodSchema: z.ZodType<
  CreateEventTypeResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateEventTypeNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEventTypeUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateEventTypeBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEventTypeResponseBody$zodSchema
  ).optional().describe("Created"),
});
