/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointAuthentication,
  EndpointAuthentication$zodSchema,
} from "./endpointauthentication.js";

export type CreateEndpoint = {
  advanced_signatures?: boolean | undefined;
  appID?: string | undefined;
  authentication?: EndpointAuthentication | undefined;
  description?: string | undefined;
  http_timeout?: number | undefined;
  is_disabled?: boolean | undefined;
  name: string;
  owner_id?: string | undefined;
  rate_limit?: number | undefined;
  rate_limit_duration?: number | undefined;
  secret?: string | undefined;
  slack_webhook_url?: string | undefined;
  support_email?: string | undefined;
  url: string;
};

export const CreateEndpoint$zodSchema: z.ZodType<
  CreateEndpoint,
  z.ZodTypeDef,
  unknown
> = z.object({
  advanced_signatures: z.boolean().optional(),
  appID: z.string().optional(),
  authentication: EndpointAuthentication$zodSchema.optional(),
  description: z.string().optional(),
  http_timeout: z.number().int().optional(),
  is_disabled: z.boolean().optional(),
  name: z.string(),
  owner_id: z.string().optional(),
  rate_limit: z.number().int().optional(),
  rate_limit_duration: z.number().int().optional(),
  secret: z.string().optional(),
  slack_webhook_url: z.string().optional(),
  support_email: z.string().optional(),
  url: z.string(),
});
