/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateEventType = {
  category?: string | undefined;
  description?: string | undefined;
  json_schema?: { [k: string]: any } | undefined;
  name?: string | undefined;
};

export const CreateEventType$zodSchema: z.ZodType<CreateEventType> = z.object({
  category: z.string().optional().describe(
    "Category is a product-specific grouping for the event type",
  ),
  description: z.string().optional().describe(
    "Description is used to describe what the event type does",
  ),
  json_schema: z.record(z.string(), z.any()).optional().describe(
    "JSONSchema is the JSON structure of the event type",
  ),
  name: z.string().optional().describe(
    "Name is the event type name. E.g., invoice.created",
  ),
});
