/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CreateEvent, CreateEvent$zodSchema } from "./createevent.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type CreateEndpointEventRequest = {
  projectID: string;
  CreateEvent: CreateEvent;
};

export const CreateEndpointEventRequest$zodSchema: z.ZodType<
  CreateEndpointEventRequest
> = z.object({
  CreateEvent: CreateEvent$zodSchema,
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type CreateEndpointEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointEventNotFoundResponseBody$zodSchema: z.ZodType<
  CreateEndpointEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type CreateEndpointEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  CreateEndpointEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type CreateEndpointEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointEventBadRequestResponseBody$zodSchema: z.ZodType<
  CreateEndpointEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type CreateEndpointEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const CreateEndpointEventResponseBody$zodSchema: z.ZodType<
  CreateEndpointEventResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type CreateEndpointEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | CreateEndpointEventResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | CreateEndpointEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | CreateEndpointEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | CreateEndpointEventNotFoundResponseBody
    | undefined;
};

export const CreateEndpointEventResponse$zodSchema: z.ZodType<
  CreateEndpointEventResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    CreateEndpointEventNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointEventUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    CreateEndpointEventBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    CreateEndpointEventResponseBody$zodSchema
  ).optional(),
});
