/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CustomResponse, CustomResponse$zodSchema } from "./customresponse.js";
import { PubSubConfig, PubSubConfig$zodSchema } from "./pubsubconfig.js";
import { SourceProvider, SourceProvider$zodSchema } from "./sourceprovider.js";
import { SourceType, SourceType$zodSchema } from "./sourcetype.js";
import { VerifierConfig, VerifierConfig$zodSchema } from "./verifierconfig.js";

export type CreateSource = {
  body_function?: string | undefined;
  custom_response?: CustomResponse | undefined;
  header_function?: string | undefined;
  idempotency_keys?: Array<string> | undefined;
  name?: string | undefined;
  provider?: SourceProvider | undefined;
  pub_sub?: PubSubConfig | undefined;
  type?: SourceType | undefined;
  verifier?: VerifierConfig | undefined;
};

export const CreateSource$zodSchema: z.ZodType<CreateSource> = z.object({
  body_function: z.string().optional(),
  custom_response: CustomResponse$zodSchema.optional(),
  header_function: z.string().optional(),
  idempotency_keys: z.array(z.string()).optional(),
  name: z.string().optional(),
  provider: SourceProvider$zodSchema.optional(),
  pub_sub: PubSubConfig$zodSchema.optional(),
  type: SourceType$zodSchema.optional(),
  verifier: VerifierConfig$zodSchema.optional(),
});
