/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateFilterRequest = {
  body?: { [k: string]: any } | undefined;
  event_type: string;
  headers?: { [k: string]: any } | undefined;
};

export const CreateFilterRequest$zodSchema: z.ZodType<CreateFilterRequest> = z
  .object({
    body: z.record(z.string(), z.any()).optional(),
    event_type: z.string(),
    headers: z.record(z.string(), z.any()).optional(),
  });
