/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type DeleteFilterRequest = {
  projectID: string;
  subscriptionID: string;
  filterID: string;
};

export const DeleteFilterRequest$zodSchema: z.ZodType<DeleteFilterRequest> = z
  .object({
    filterID: z.string().describe("Filter ID"),
    projectID: z.string().describe("Project ID"),
    subscriptionID: z.string().describe("Subscription ID"),
  });

/**
 * Not Found
 */
export type DeleteFilterNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteFilterNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteFilterNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type DeleteFilterUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteFilterUnauthorizedResponseBody$zodSchema: z.ZodType<
  DeleteFilterUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type DeleteFilterBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteFilterBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteFilterBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type DeleteFilterResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteFilterResponseBody$zodSchema: z.ZodType<
  DeleteFilterResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type DeleteFilterResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: DeleteFilterResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | DeleteFilterBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | DeleteFilterUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | DeleteFilterNotFoundResponseBody
    | undefined;
};

export const DeleteFilterResponse$zodSchema: z.ZodType<DeleteFilterResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      DeleteFilterNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      DeleteFilterUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      DeleteFilterBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      DeleteFilterResponseBody$zodSchema
    ).optional().describe("OK"),
  });
