/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type DeleteSourceRequest = { projectID: string; sourceID: string };

export const DeleteSourceRequest$zodSchema: z.ZodType<DeleteSourceRequest> = z
  .object({
    projectID: z.string().describe("Project ID"),
    sourceID: z.string().describe("source id"),
  });

/**
 * Not Found
 */
export type DeleteSourceNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSourceNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteSourceNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type DeleteSourceUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSourceUnauthorizedResponseBody$zodSchema: z.ZodType<
  DeleteSourceUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type DeleteSourceBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSourceBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteSourceBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type DeleteSourceResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSourceResponseBody$zodSchema: z.ZodType<
  DeleteSourceResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type DeleteSourceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: DeleteSourceResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | DeleteSourceBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | DeleteSourceUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | DeleteSourceNotFoundResponseBody
    | undefined;
};

export const DeleteSourceResponse$zodSchema: z.ZodType<DeleteSourceResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      DeleteSourceNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      DeleteSourceUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      DeleteSourceBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      DeleteSourceResponseBody$zodSchema
    ).optional().describe("OK"),
  });
