/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type DeleteEndpointRequest = { projectID: string; endpointID: string };

export const DeleteEndpointRequest$zodSchema: z.ZodType<DeleteEndpointRequest> =
  z.object({
    endpointID: z.string().describe("Endpoint ID"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type DeleteEndpointNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteEndpointNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteEndpointNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type DeleteEndpointUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteEndpointUnauthorizedResponseBody$zodSchema: z.ZodType<
  DeleteEndpointUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type DeleteEndpointBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteEndpointBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteEndpointBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type DeleteEndpointResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteEndpointResponseBody$zodSchema: z.ZodType<
  DeleteEndpointResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type DeleteEndpointResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: DeleteEndpointResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | DeleteEndpointBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | DeleteEndpointUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | DeleteEndpointNotFoundResponseBody
    | undefined;
};

export const DeleteEndpointResponse$zodSchema: z.ZodType<
  DeleteEndpointResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    DeleteEndpointNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    DeleteEndpointUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    DeleteEndpointBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    DeleteEndpointResponseBody$zodSchema
  ).optional().describe("OK"),
});
