/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type DeleteSubscriptionRequest = {
  projectID: string;
  subscriptionID: string;
};

export const DeleteSubscriptionRequest$zodSchema: z.ZodType<
  DeleteSubscriptionRequest
> = z.object({
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("subscription id"),
});

/**
 * Not Found
 */
export type DeleteSubscriptionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSubscriptionNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteSubscriptionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type DeleteSubscriptionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSubscriptionUnauthorizedResponseBody$zodSchema: z.ZodType<
  DeleteSubscriptionUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type DeleteSubscriptionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSubscriptionBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteSubscriptionBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type DeleteSubscriptionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const DeleteSubscriptionResponseBody$zodSchema: z.ZodType<
  DeleteSubscriptionResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type DeleteSubscriptionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: DeleteSubscriptionResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | DeleteSubscriptionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | DeleteSubscriptionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | DeleteSubscriptionNotFoundResponseBody
    | undefined;
};

export const DeleteSubscriptionResponse$zodSchema: z.ZodType<
  DeleteSubscriptionResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    DeleteSubscriptionNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    DeleteSubscriptionUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    DeleteSubscriptionBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    DeleteSubscriptionResponseBody$zodSchema
  ).optional().describe("OK"),
});
