/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeliveryAttempt = {
  api_version?: string | undefined;
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  endpoint_id?: string | undefined;
  error?: string | undefined;
  http_status?: string | undefined;
  ip_address?: string | undefined;
  method?: string | undefined;
  msg_id?: string | undefined;
  project_id?: string | undefined;
  request_http_header?: { [k: string]: string } | undefined;
  response_data?: string | undefined;
  response_http_header?: { [k: string]: string } | undefined;
  status?: boolean | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  url?: string | undefined;
};

export const DeliveryAttempt$zodSchema: z.ZodType<DeliveryAttempt> = z.object({
  api_version: z.string().optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional(),
  endpoint_id: z.string().optional(),
  error: z.string().optional(),
  http_status: z.string().optional(),
  ip_address: z.string().optional(),
  method: z.string().optional(),
  msg_id: z.string().optional(),
  project_id: z.string().optional(),
  request_http_header: z.record(z.string(), z.string()).optional(),
  response_data: z.string().optional(),
  response_http_header: z.record(z.string(), z.string()).optional(),
  status: z.boolean().optional(),
  uid: z.string().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
});
