/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

export const DeliveryMode = {
  AtLeastOnce: "at_least_once",
  AtMostOnce: "at_most_once",
} as const;
export type DeliveryMode = OpenEnum<typeof DeliveryMode>;

export const DeliveryMode$zodSchema = z.union([
  z.enum([
    "at_least_once",
    "at_most_once",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]);
