/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { DeviceStatus, DeviceStatus$zodSchema } from "./devicestatus.js";

export type Device = {
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  endpoint_id?: string | undefined;
  host_name?: string | undefined;
  last_seen_at?: string | undefined;
  project_id?: string | undefined;
  status?: DeviceStatus | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
};

export const Device$zodSchema: z.ZodType<Device> = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional(),
  endpoint_id: z.string().optional(),
  host_name: z.string().optional(),
  last_seen_at: z.string().optional(),
  project_id: z.string().optional(),
  status: DeviceStatus$zodSchema.optional(),
  uid: z.string().optional(),
  updated_at: z.string().optional(),
});
