/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Data is an arbitrary JSON value that gets sent as the body of the
 *
 * @remarks
 * webhook to the endpoints
 */
export type DynamicEventData = {};

export const DynamicEventData$zodSchema: z.ZodType<DynamicEventData> = z.object(
  {},
).describe(
  "Data is an arbitrary JSON value that gets sent as the body of the\n"
    + "webhook to the endpoints",
);

export type DynamicEvent = {
  custom_headers?: { [k: string]: string } | undefined;
  data?: DynamicEventData | undefined;
  event_type?: string | undefined;
  event_types?: Array<string> | undefined;
  idempotency_key?: string | undefined;
  secret?: string | undefined;
  url?: string | undefined;
};

export const DynamicEvent$zodSchema: z.ZodType<DynamicEvent> = z.object({
  custom_headers: z.record(z.string(), z.string()).optional(),
  data: z.lazy(() => DynamicEventData$zodSchema).optional(),
  event_type: z.string().optional(),
  event_types: z.array(z.string()).optional(),
  idempotency_key: z.string().optional(),
  secret: z.string().optional(),
  url: z.string().optional(),
});
