/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EncodingType = {
  Base64: "base64",
  Hex: "hex",
} as const;
export type EncodingType = ClosedEnum<typeof EncodingType>;

export const EncodingType$zodSchema = z.enum([
  "base64",
  "hex",
]);
