/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointAuthentication,
  EndpointAuthentication$zodSchema,
} from "./endpointauthentication.js";
import { EndpointStatus, EndpointStatus$zodSchema } from "./endpointstatus.js";
import { Secret, Secret$zodSchema } from "./secret.js";

export type Endpoint = {
  advanced_signatures?: boolean | undefined;
  authentication?: EndpointAuthentication | undefined;
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  description?: string | undefined;
  events?: number | undefined;
  failure_rate?: number | undefined;
  http_timeout?: number | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
  project_id?: string | undefined;
  rate_limit?: number | undefined;
  rate_limit_duration?: number | undefined;
  secrets?: Array<Secret> | undefined;
  slack_webhook_url?: string | undefined;
  status?: EndpointStatus | undefined;
  support_email?: string | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  url?: string | undefined;
};

export const Endpoint$zodSchema: z.ZodType<Endpoint> = z.object({
  advanced_signatures: z.boolean().optional(),
  authentication: EndpointAuthentication$zodSchema.optional(),
  created_at: z.string().optional(),
  deleted_at: z.string().optional(),
  description: z.string().optional(),
  events: z.int().optional(),
  failure_rate: z.number().optional(),
  http_timeout: z.int().optional(),
  name: z.string().optional(),
  owner_id: z.string().optional(),
  project_id: z.string().optional(),
  rate_limit: z.int().optional(),
  rate_limit_duration: z.int().optional(),
  secrets: z.array(Secret$zodSchema).optional(),
  slack_webhook_url: z.string().optional(),
  status: EndpointStatus$zodSchema.optional(),
  support_email: z.string().optional(),
  uid: z.string().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
});
