/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const EndpointAuthenticationType$zodSchema = z.enum([
  "api_key",
]);

export type EndpointAuthenticationType = z.infer<
  typeof EndpointAuthenticationType$zodSchema
>;
