/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EndpointStatus = {
  Active: "active",
  Inactive: "inactive",
  Pending: "pending",
  Paused: "paused",
} as const;
export type EndpointStatus = ClosedEnum<typeof EndpointStatus>;

export const EndpointStatus$zodSchema = z.enum([
  "active",
  "inactive",
  "pending",
  "paused",
]);
