/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EventDeliveryStatus = {
  Scheduled: "Scheduled",
  Processing: "Processing",
  Discarded: "Discarded",
  Failure: "Failure",
  Success: "Success",
  Retry: "Retry",
} as const;
export type EventDeliveryStatus = ClosedEnum<typeof EventDeliveryStatus>;

export const EventDeliveryStatus$zodSchema = z.enum([
  "Scheduled",
  "Processing",
  "Discarded",
  "Failure",
  "Success",
  "Retry",
]);
