/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CLIMetadata, CLIMetadata$zodSchema } from "./climetadata.js";
import { DeliveryMode, DeliveryMode$zodSchema } from "./deliverymode.js";
import { Device, Device$zodSchema } from "./device.js";
import { Endpoint, Endpoint$zodSchema } from "./endpoint.js";
import { Event, Event$zodSchema } from "./event.js";
import {
  EventDeliveryStatus,
  EventDeliveryStatus$zodSchema,
} from "./eventdeliverystatus.js";
import { Metadata, Metadata$zodSchema } from "./metadata.js";
import { Source, Source$zodSchema } from "./source.js";

export type EventDeliveryResponse = {
  acknowledged_at?: string | undefined;
  cli_metadata?: CLIMetadata | undefined;
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  delivery_mode?: DeliveryMode | undefined;
  description?: string | undefined;
  device_id?: string | undefined;
  device_metadata?: Device | undefined;
  endpoint_id?: string | undefined;
  endpoint_metadata?: Endpoint | undefined;
  event_id?: string | undefined;
  event_metadata?: Event | undefined;
  event_type?: string | undefined;
  headers?: { [k: string]: Array<string> } | undefined;
  idempotency_key?: string | undefined;
  latency?: string | undefined;
  latency_seconds?: number | undefined;
  metadata?: Metadata | undefined;
  project_id?: string | undefined;
  source_metadata?: Source | undefined;
  status?: EventDeliveryStatus | undefined;
  subscription_id?: string | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  url_query_params?: string | undefined;
};

export const EventDeliveryResponse$zodSchema: z.ZodType<EventDeliveryResponse> =
  z.object({
    acknowledged_at: z.string().optional(),
    cli_metadata: CLIMetadata$zodSchema.optional(),
    created_at: z.string().optional(),
    deleted_at: z.string().optional(),
    delivery_mode: DeliveryMode$zodSchema.optional(),
    description: z.string().optional(),
    device_id: z.string().optional(),
    device_metadata: Device$zodSchema.optional(),
    endpoint_id: z.string().optional(),
    endpoint_metadata: Endpoint$zodSchema.optional(),
    event_id: z.string().optional(),
    event_metadata: Event$zodSchema.optional(),
    event_type: z.string().optional(),
    headers: z.record(z.string(), z.array(z.string())).optional(),
    idempotency_key: z.string().optional(),
    latency: z.string().optional(),
    latency_seconds: z.number().optional(),
    metadata: Metadata$zodSchema.optional(),
    project_id: z.string().optional(),
    source_metadata: Source$zodSchema.optional(),
    status: EventDeliveryStatus$zodSchema.optional(),
    subscription_id: z.string().optional(),
    uid: z.string().optional(),
    updated_at: z.string().optional(),
    url_query_params: z.string().optional(),
  });
