/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EventStatus = {
  Processing: "Processing",
  Failure: "Failure",
  Success: "Success",
  Retry: "Retry",
  Pending: "Pending",
} as const;
export type EventStatus = ClosedEnum<typeof EventStatus>;

export const EventStatus$zodSchema = z.enum([
  "Processing",
  "Failure",
  "Success",
  "Retry",
  "Pending",
]);
