/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ExpireSecret = {
  expiration?: number | undefined;
  secret?: string | undefined;
};

export const ExpireSecret$zodSchema: z.ZodType<ExpireSecret> = z.object({
  expiration: z.int().optional(),
  secret: z.string().optional(),
});
