/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ExpireSecret, ExpireSecret$zodSchema } from "./expiresecret.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ExpireSecretRequest = {
  projectID: string;
  endpointID: string;
  ExpireSecret: ExpireSecret;
};

export const ExpireSecretRequest$zodSchema: z.ZodType<ExpireSecretRequest> = z
  .object({
    ExpireSecret: ExpireSecret$zodSchema.describe(
      "Expire Secret Body Parameters",
    ),
    endpointID: z.string().describe("Endpoint ID"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type ExpireSecretNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ExpireSecretNotFoundResponseBody$zodSchema: z.ZodType<
  ExpireSecretNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type ExpireSecretUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ExpireSecretUnauthorizedResponseBody$zodSchema: z.ZodType<
  ExpireSecretUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type ExpireSecretBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ExpireSecretBadRequestResponseBody$zodSchema: z.ZodType<
  ExpireSecretBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type ExpireSecretResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EndpointResponse | undefined;
};

export const ExpireSecretResponseBody$zodSchema: z.ZodType<
  ExpireSecretResponseBody
> = z.object({
  data: EndpointResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type ExpireSecretResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: ExpireSecretResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | ExpireSecretBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ExpireSecretUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ExpireSecretNotFoundResponseBody
    | undefined;
};

export const ExpireSecretResponse$zodSchema: z.ZodType<ExpireSecretResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      ExpireSecretNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      ExpireSecretUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      ExpireSecretBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      ExpireSecretResponseBody$zodSchema
    ).optional().describe("OK"),
  });
