/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ExpireSecret = {
  expiration?: number | undefined;
  secret?: string | undefined;
};

export const ExpireSecret$zodSchema: z.ZodType<ExpireSecret> = z.object({
  expiration: z.int().optional().describe(
    "Amount of time to wait before expiring the old endpoint secret.\nIf AdvancedSignatures is turned on for the project, signatures for both secrets will be generated up until\nthe old signature is expired.",
  ),
  secret: z.string().optional().describe("New Endpoint secret value."),
});
