/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Data is an arbitrary JSON value that gets sent as the body of the
 *
 * @remarks
 * webhook to the endpoints
 */
export type FanoutEventData = {};

export const FanoutEventData$zodSchema: z.ZodType<FanoutEventData> = z.object(
  {},
).describe(
  "Data is an arbitrary JSON value that gets sent as the body of the\nwebhook to the endpoints",
);

export type FanoutEvent = {
  custom_headers?: { [k: string]: string } | undefined;
  data?: FanoutEventData | undefined;
  event_type?: string | undefined;
  idempotency_key?: string | undefined;
  owner_id?: string | undefined;
};

export const FanoutEvent$zodSchema: z.ZodType<FanoutEvent> = z.object({
  custom_headers: z.record(z.string(), z.string()).optional().describe(
    "Specifies custom headers you want convoy to add when the event is dispatched to your endpoint",
  ),
  data: z.lazy(() => FanoutEventData$zodSchema).optional().describe(
    "Data is an arbitrary JSON value that gets sent as the body of the\nwebhook to the endpoints",
  ),
  event_type: z.string().optional().describe(
    "Event Type is used for filtering and debugging e.g invoice.paid",
  ),
  idempotency_key: z.string().optional().describe(
    "Specify a key for event deduplication",
  ),
  owner_id: z.string().optional().describe(
    "Used for fanout, sends this event to all endpoints with this OwnerID.",
  ),
});
