/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FilterSchema = { body?: any | undefined; header?: any | undefined };

export const FilterSchema$zodSchema: z.ZodType<FilterSchema> = z.object({
  body: z.any().optional(),
  header: z.any().optional(),
});
