/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Fs, Fs$zodSchema } from "./fs.js";

export type FilterConfiguration = {
  event_types?: Array<string> | undefined;
  filter?: Fs | undefined;
};

export const FilterConfiguration$zodSchema: z.ZodType<FilterConfiguration> = z
  .object({
    event_types: z.array(z.string()).optional(),
    filter: Fs$zodSchema.optional(),
  });
