/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IDs, IDs$zodSchema } from "./ids.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ForceResendEventDeliveriesRequest = { projectID: string; IDs: IDs };

export const ForceResendEventDeliveriesRequest$zodSchema: z.ZodType<
  ForceResendEventDeliveriesRequest
> = z.object({
  IDs: IDs$zodSchema.describe("event delivery ids"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type ForceResendEventDeliveriesNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ForceResendEventDeliveriesNotFoundResponseBody$zodSchema:
  z.ZodType<ForceResendEventDeliveriesNotFoundResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Not Found");

/**
 * Unauthorized
 */
export type ForceResendEventDeliveriesUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ForceResendEventDeliveriesUnauthorizedResponseBody$zodSchema:
  z.ZodType<ForceResendEventDeliveriesUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type ForceResendEventDeliveriesBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ForceResendEventDeliveriesBadRequestResponseBody$zodSchema:
  z.ZodType<ForceResendEventDeliveriesBadRequestResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Bad Request");

/**
 * OK
 */
export type ForceResendEventDeliveriesResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ForceResendEventDeliveriesResponseBody$zodSchema: z.ZodType<
  ForceResendEventDeliveriesResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type ForceResendEventDeliveriesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | ForceResendEventDeliveriesResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | ForceResendEventDeliveriesBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ForceResendEventDeliveriesUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ForceResendEventDeliveriesNotFoundResponseBody
    | undefined;
};

export const ForceResendEventDeliveriesResponse$zodSchema: z.ZodType<
  ForceResendEventDeliveriesResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    ForceResendEventDeliveriesNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ForceResendEventDeliveriesUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    ForceResendEventDeliveriesBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    ForceResendEventDeliveriesResponseBody$zodSchema
  ).optional().describe("OK"),
});
