/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FunctionRequest = {
  function?: string | undefined;
  payload?: { [k: string]: any } | undefined;
  type?: string | undefined;
};

export const FunctionRequest$zodSchema: z.ZodType<FunctionRequest> = z.object({
  function: z.string().optional(),
  payload: z.record(z.string(), z.any()).optional(),
  type: z.string().optional(),
});
