/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FunctionResponse = {
  log?: Array<string> | undefined;
  payload?: any | undefined;
};

export const FunctionResponse$zodSchema: z.ZodType<FunctionResponse> = z.object(
  {
    log: z.array(z.string()).optional(),
    payload: z.any().optional(),
  },
);
