/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  PortalLinkResponse,
  PortalLinkResponse$zodSchema,
} from "./portallinkresponse.js";

export type GeneratePortalTokenRequest = {
  projectID: string;
  portalLinkID: string;
};

export const GeneratePortalTokenRequest$zodSchema: z.ZodType<
  GeneratePortalTokenRequest
> = z.object({
  portalLinkID: z.string().describe("portal link id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GeneratePortalTokenNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GeneratePortalTokenNotFoundResponseBody$zodSchema: z.ZodType<
  GeneratePortalTokenNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GeneratePortalTokenUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GeneratePortalTokenUnauthorizedResponseBody$zodSchema: z.ZodType<
  GeneratePortalTokenUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GeneratePortalTokenBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GeneratePortalTokenBadRequestResponseBody$zodSchema: z.ZodType<
  GeneratePortalTokenBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GeneratePortalTokenResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: PortalLinkResponse | undefined;
};

export const GeneratePortalTokenResponseBody$zodSchema: z.ZodType<
  GeneratePortalTokenResponseBody
> = z.object({
  data: PortalLinkResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GeneratePortalTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GeneratePortalTokenResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GeneratePortalTokenBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GeneratePortalTokenUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GeneratePortalTokenNotFoundResponseBody
    | undefined;
};

export const GeneratePortalTokenResponse$zodSchema: z.ZodType<
  GeneratePortalTokenResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GeneratePortalTokenNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GeneratePortalTokenUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GeneratePortalTokenBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GeneratePortalTokenResponseBody$zodSchema
  ).optional(),
});
