/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeliveryAttempt,
  DeliveryAttempt$zodSchema,
} from "./deliveryattempt.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetDeliveryAttemptRequest = {
  projectID: string;
  eventDeliveryID: string;
  deliveryAttemptID: string;
};

export const GetDeliveryAttemptRequest$zodSchema: z.ZodType<
  GetDeliveryAttemptRequest
> = z.object({
  deliveryAttemptID: z.string().describe("delivery attempt id"),
  eventDeliveryID: z.string().describe("event delivery id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GetDeliveryAttemptNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptNotFoundResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetDeliveryAttemptUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetDeliveryAttemptBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptBadRequestResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetDeliveryAttemptResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: DeliveryAttempt | undefined;
};

export const GetDeliveryAttemptResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptResponseBody
> = z.object({
  data: DeliveryAttempt$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetDeliveryAttemptResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetDeliveryAttemptResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetDeliveryAttemptBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetDeliveryAttemptUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetDeliveryAttemptNotFoundResponseBody
    | undefined;
};

export const GetDeliveryAttemptResponse$zodSchema: z.ZodType<
  GetDeliveryAttemptResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptResponseBody$zodSchema
  ).optional(),
});
