/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeliveryAttempt,
  DeliveryAttempt$zodSchema,
} from "./deliveryattempt.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetDeliveryAttemptsRequest = {
  projectID: string;
  eventDeliveryID: string;
};

export const GetDeliveryAttemptsRequest$zodSchema: z.ZodType<
  GetDeliveryAttemptsRequest
> = z.object({
  eventDeliveryID: z.string().describe("event delivery id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GetDeliveryAttemptsNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptsNotFoundResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptsNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetDeliveryAttemptsUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptsUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptsUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetDeliveryAttemptsBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetDeliveryAttemptsBadRequestResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptsBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetDeliveryAttemptsResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<DeliveryAttempt> | undefined;
};

export const GetDeliveryAttemptsResponseBody$zodSchema: z.ZodType<
  GetDeliveryAttemptsResponseBody
> = z.object({
  data: z.array(DeliveryAttempt$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetDeliveryAttemptsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetDeliveryAttemptsResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetDeliveryAttemptsBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetDeliveryAttemptsUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetDeliveryAttemptsNotFoundResponseBody
    | undefined;
};

export const GetDeliveryAttemptsResponse$zodSchema: z.ZodType<
  GetDeliveryAttemptsResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptsUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptsBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetDeliveryAttemptsResponseBody$zodSchema
  ).optional(),
});
