/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { EventResponse, EventResponse$zodSchema } from "./eventresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";

export const GetEventsPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetEventsPagedDirection = ClosedEnum<
  typeof GetEventsPagedDirection
>;

export const GetEventsPagedDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type GetEventsPagedRequest = {
  projectID: string;
  direction?: GetEventsPagedDirection | undefined;
  endDate?: string | undefined;
  endpointId?: Array<string> | undefined;
  idempotencyKey?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  query?: string | undefined;
  sort?: string | undefined;
  sourceId?: Array<string> | undefined;
  startDate?: string | undefined;
};

export const GetEventsPagedRequest$zodSchema: z.ZodType<GetEventsPagedRequest> =
  z.object({
    direction: GetEventsPagedDirection$zodSchema.optional(),
    endDate: z.string().describe("The end date").optional(),
    endpointId: z.array(z.string()).describe(
      "A list of endpoint ids to filter by",
    ).optional(),
    idempotencyKey: z.string().describe("IdempotencyKey to filter by")
      .optional(),
    next_page_cursor: z.string().describe(
      "A pagination cursor to fetch the next page of a list",
    ).optional(),
    perPage: z.int().describe("The number of items to return per page")
      .optional(),
    prev_page_cursor: z.string().describe(
      "A pagination cursor to fetch the previous page of a list",
    ).optional(),
    projectID: z.string().describe("Project ID"),
    query: z.string().describe(
      "Any arbitrary value to filter the events payload",
    ).optional(),
    sort: z.string().describe(
      "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
    ).optional(),
    sourceId: z.array(z.string()).describe(
      "A list of Source IDs to filter the events by.",
    ).optional(),
    startDate: z.string().describe("The start date").optional(),
  });

/**
 * Not Found
 */
export type GetEventsPagedNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventsPagedNotFoundResponseBody$zodSchema: z.ZodType<
  GetEventsPagedNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEventsPagedUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventsPagedUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetEventsPagedUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEventsPagedBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventsPagedBadRequestResponseBody$zodSchema: z.ZodType<
  GetEventsPagedBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type GetEventsPagedData = {
  content?: Array<EventResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const GetEventsPagedData$zodSchema: z.ZodType<GetEventsPagedData> = z
  .object({
    content: z.array(EventResponse$zodSchema).optional(),
    pagination: PaginationData$zodSchema.optional(),
  });

/**
 * OK
 */
export type GetEventsPagedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetEventsPagedData | undefined;
};

export const GetEventsPagedResponseBody$zodSchema: z.ZodType<
  GetEventsPagedResponseBody
> = z.object({
  data: z.lazy(() => GetEventsPagedData$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEventsPagedResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetEventsPagedResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetEventsPagedBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEventsPagedUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEventsPagedNotFoundResponseBody
    | undefined;
};

export const GetEventsPagedResponse$zodSchema: z.ZodType<
  GetEventsPagedResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEventsPagedNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEventsPagedUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEventsPagedBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEventsPagedResponseBody$zodSchema
  ).optional(),
});
