/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EventResponse, EventResponse$zodSchema } from "./eventresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetEndpointEventRequest = { projectID: string; eventID: string };

export const GetEndpointEventRequest$zodSchema: z.ZodType<
  GetEndpointEventRequest
> = z.object({
  eventID: z.string().describe("event id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GetEndpointEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointEventNotFoundResponseBody$zodSchema: z.ZodType<
  GetEndpointEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEndpointEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetEndpointEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEndpointEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointEventBadRequestResponseBody$zodSchema: z.ZodType<
  GetEndpointEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetEndpointEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EventResponse | undefined;
};

export const GetEndpointEventResponseBody$zodSchema: z.ZodType<
  GetEndpointEventResponseBody
> = z.object({
  data: EventResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEndpointEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetEndpointEventResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetEndpointEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEndpointEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEndpointEventNotFoundResponseBody
    | undefined;
};

export const GetEndpointEventResponse$zodSchema: z.ZodType<
  GetEndpointEventResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEndpointEventNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEndpointEventUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointEventBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointEventResponseBody$zodSchema
  ).optional(),
});
