/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetEndpointRequest = { projectID: string; endpointID: string };

export const GetEndpointRequest$zodSchema: z.ZodType<
  GetEndpointRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  endpointID: z.string().describe("Endpoint ID"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GetEndpointNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointNotFoundResponseBody$zodSchema: z.ZodType<
  GetEndpointNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEndpointUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetEndpointUnauthorizedResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEndpointBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointBadRequestResponseBody$zodSchema: z.ZodType<
  GetEndpointBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetEndpointResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EndpointResponse | undefined;
};

export const GetEndpointResponseBody$zodSchema: z.ZodType<
  GetEndpointResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: EndpointResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEndpointResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetEndpointResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetEndpointBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEndpointUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEndpointNotFoundResponseBody
    | undefined;
};

export const GetEndpointResponse$zodSchema: z.ZodType<
  GetEndpointResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEndpointNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEndpointUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointResponseBody$zodSchema
  ).optional(),
});
