/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  EventDeliveryResponse,
  EventDeliveryResponse$zodSchema,
} from "./eventdeliveryresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";

export const GetEventDeliveriesPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetEventDeliveriesPagedDirection = ClosedEnum<
  typeof GetEventDeliveriesPagedDirection
>;

export const GetEventDeliveriesPagedDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type GetEventDeliveriesPagedRequest = {
  projectID: string;
  direction?: GetEventDeliveriesPagedDirection | undefined;
  endDate?: string | undefined;
  endpointId?: Array<string> | undefined;
  eventId?: string | undefined;
  event_type?: string | undefined;
  idempotencyKey?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  sort?: string | undefined;
  startDate?: string | undefined;
  status?: Array<string> | undefined;
  subscriptionId?: string | undefined;
};

export const GetEventDeliveriesPagedRequest$zodSchema: z.ZodType<
  GetEventDeliveriesPagedRequest
> = z.object({
  direction: GetEventDeliveriesPagedDirection$zodSchema.optional(),
  endDate: z.string().describe("The end date").optional(),
  endpointId: z.array(z.string()).describe(
    "A list of endpoint IDs to filter by",
  ).optional(),
  eventId: z.string().describe("Event ID to filter by").optional(),
  event_type: z.string().describe("EventType to filter by").optional(),
  idempotencyKey: z.string().describe("IdempotencyKey to filter by").optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  perPage: z.int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
  startDate: z.string().describe("The start date").optional(),
  status: z.array(z.string()).describe(
    "A list of event delivery statuses to filter by",
  ).optional(),
  subscriptionId: z.string().describe("SubscriptionID to filter by").optional(),
});

/**
 * Not Found
 */
export type GetEventDeliveriesPagedNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveriesPagedNotFoundResponseBody$zodSchema: z.ZodType<
  GetEventDeliveriesPagedNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEventDeliveriesPagedUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveriesPagedUnauthorizedResponseBody$zodSchema:
  z.ZodType<GetEventDeliveriesPagedUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEventDeliveriesPagedBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveriesPagedBadRequestResponseBody$zodSchema: z.ZodType<
  GetEventDeliveriesPagedBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type GetEventDeliveriesPagedData = {
  content?: Array<EventDeliveryResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const GetEventDeliveriesPagedData$zodSchema: z.ZodType<
  GetEventDeliveriesPagedData
> = z.object({
  content: z.array(EventDeliveryResponse$zodSchema).optional(),
  pagination: PaginationData$zodSchema.optional(),
});

/**
 * OK
 */
export type GetEventDeliveriesPagedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetEventDeliveriesPagedData | undefined;
};

export const GetEventDeliveriesPagedResponseBody$zodSchema: z.ZodType<
  GetEventDeliveriesPagedResponseBody
> = z.object({
  data: z.lazy(() => GetEventDeliveriesPagedData$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEventDeliveriesPagedResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | GetEventDeliveriesPagedResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | GetEventDeliveriesPagedBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEventDeliveriesPagedUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEventDeliveriesPagedNotFoundResponseBody
    | undefined;
};

export const GetEventDeliveriesPagedResponse$zodSchema: z.ZodType<
  GetEventDeliveriesPagedResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEventDeliveriesPagedNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEventDeliveriesPagedUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEventDeliveriesPagedBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEventDeliveriesPagedResponseBody$zodSchema
  ).optional().describe("OK"),
});
