/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";

export const Direction$zodSchema = z.enum([
  "next",
  "prev",
]);

export type Direction = z.infer<typeof Direction$zodSchema>;

export type CustomerIdSpecial = string | Array<string>;

export const CustomerIdSpecial$zodSchema: z.ZodType<
  CustomerIdSpecial,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.array(z.string()),
]);

export type GetEndpointsRequest = {
  projectID: string;
  direction?: Direction | undefined;
  next_page_cursor?: string | undefined;
  ownerId?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  q?: string | undefined;
  sort?: string | undefined;
  customer_id_special?: string | Array<string> | undefined;
};

export const GetEndpointsRequest$zodSchema: z.ZodType<
  GetEndpointsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  customer_id_special: z.union([
    z.string(),
    z.array(z.string()),
  ]).optional(),
  direction: Direction$zodSchema.optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  ownerId: z.string().describe("The owner ID of the endpoint").optional(),
  perPage: z.number().int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  q: z.string().describe("The name of the endpoint").optional(),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
});

/**
 * Not Found
 */
export type GetEndpointsNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointsNotFoundResponseBody$zodSchema: z.ZodType<
  GetEndpointsNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEndpointsUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointsUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetEndpointsUnauthorizedResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEndpointsBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEndpointsBadRequestResponseBody$zodSchema: z.ZodType<
  GetEndpointsBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type Data = {
  content?: Array<EndpointResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const Data$zodSchema: z.ZodType<Data, z.ZodTypeDef, unknown> = z.object({
  content: z.array(EndpointResponse$zodSchema).optional(),
  pagination: PaginationData$zodSchema.optional(),
});

/**
 * OK
 */
export type GetEndpointsResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Data | undefined;
};

export const GetEndpointsResponseBody$zodSchema: z.ZodType<
  GetEndpointsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => Data$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEndpointsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetEndpointsResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetEndpointsBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEndpointsUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEndpointsNotFoundResponseBody
    | undefined;
};

export const GetEndpointsResponse$zodSchema: z.ZodType<
  GetEndpointsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEndpointsNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEndpointsUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointsBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEndpointsResponseBody$zodSchema
  ).optional(),
});
