/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EventDeliveryResponse,
  EventDeliveryResponse$zodSchema,
} from "./eventdeliveryresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetEventDeliveryRequest = {
  projectID: string;
  eventDeliveryID: string;
};

export const GetEventDeliveryRequest$zodSchema: z.ZodType<
  GetEventDeliveryRequest
> = z.object({
  eventDeliveryID: z.string().describe("event delivery id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type GetEventDeliveryNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveryNotFoundResponseBody$zodSchema: z.ZodType<
  GetEventDeliveryNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetEventDeliveryUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveryUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetEventDeliveryUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetEventDeliveryBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetEventDeliveryBadRequestResponseBody$zodSchema: z.ZodType<
  GetEventDeliveryBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetEventDeliveryResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EventDeliveryResponse | undefined;
};

export const GetEventDeliveryResponseBody$zodSchema: z.ZodType<
  GetEventDeliveryResponseBody
> = z.object({
  data: EventDeliveryResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetEventDeliveryResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetEventDeliveryResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetEventDeliveryBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetEventDeliveryUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetEventDeliveryNotFoundResponseBody
    | undefined;
};

export const GetEventDeliveryResponse$zodSchema: z.ZodType<
  GetEventDeliveryResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetEventDeliveryNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetEventDeliveryUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetEventDeliveryBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetEventDeliveryResponseBody$zodSchema
  ).optional().describe("OK"),
});
