/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetFiltersRequest = { projectID: string; subscriptionID: string };

export const GetFiltersRequest$zodSchema: z.ZodType<GetFiltersRequest> = z
  .object({
    projectID: z.string().describe("Project ID"),
    subscriptionID: z.string().describe("Subscription ID"),
  });

/**
 * Not Found
 */
export type GetFiltersNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFiltersNotFoundResponseBody$zodSchema: z.ZodType<
  GetFiltersNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetFiltersUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFiltersUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetFiltersUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetFiltersBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFiltersBadRequestResponseBody$zodSchema: z.ZodType<
  GetFiltersBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetFiltersResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<FilterResponse> | undefined;
};

export const GetFiltersResponseBody$zodSchema: z.ZodType<
  GetFiltersResponseBody
> = z.object({
  data: z.array(FilterResponse$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetFiltersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetFiltersResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetFiltersBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetFiltersUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetFiltersNotFoundResponseBody
    | undefined;
};

export const GetFiltersResponse$zodSchema: z.ZodType<GetFiltersResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      GetFiltersNotFoundResponseBody$zodSchema
    ).optional(),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      GetFiltersUnauthorizedResponseBody$zodSchema
    ).optional(),
    fourHundredApplicationJsonObject: z.lazy(() =>
      GetFiltersBadRequestResponseBody$zodSchema
    ).optional(),
    twoHundredApplicationJsonObject: z.lazy(() =>
      GetFiltersResponseBody$zodSchema
    ).optional(),
  });
