/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetFilterRequest = {
  projectID: string;
  subscriptionID: string;
  filterID: string;
};

export const GetFilterRequest$zodSchema: z.ZodType<GetFilterRequest> = z.object(
  {
    filterID: z.string().describe("Filter ID"),
    projectID: z.string().describe("Project ID"),
    subscriptionID: z.string().describe("Subscription ID"),
  },
);

/**
 * Not Found
 */
export type GetFilterNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFilterNotFoundResponseBody$zodSchema: z.ZodType<
  GetFilterNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetFilterUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFilterUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetFilterUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetFilterBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetFilterBadRequestResponseBody$zodSchema: z.ZodType<
  GetFilterBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetFilterResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: FilterResponse | undefined;
};

export const GetFilterResponseBody$zodSchema: z.ZodType<GetFilterResponseBody> =
  z.object({
    data: FilterResponse$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("OK");

export type GetFilterResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetFilterResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetFilterBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetFilterUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetFilterNotFoundResponseBody
    | undefined;
};

export const GetFilterResponse$zodSchema: z.ZodType<GetFilterResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      GetFilterNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      GetFilterUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      GetFilterBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      GetFilterResponseBody$zodSchema
    ).optional().describe("OK"),
  });
