/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MetaEventResponse,
  MetaEventResponse$zodSchema,
} from "./metaeventresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type GetMetaEventRequest = { projectID: string; metaEventID: string };

export const GetMetaEventRequest$zodSchema: z.ZodType<GetMetaEventRequest> = z
  .object({
    metaEventID: z.string().describe("meta event id"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type GetMetaEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetMetaEventNotFoundResponseBody$zodSchema: z.ZodType<
  GetMetaEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetMetaEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetMetaEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetMetaEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetMetaEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetMetaEventBadRequestResponseBody$zodSchema: z.ZodType<
  GetMetaEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetMetaEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: MetaEventResponse | undefined;
};

export const GetMetaEventResponseBody$zodSchema: z.ZodType<
  GetMetaEventResponseBody
> = z.object({
  data: MetaEventResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetMetaEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetMetaEventResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetMetaEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetMetaEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetMetaEventNotFoundResponseBody
    | undefined;
};

export const GetMetaEventResponse$zodSchema: z.ZodType<GetMetaEventResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      GetMetaEventNotFoundResponseBody$zodSchema
    ).optional(),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      GetMetaEventUnauthorizedResponseBody$zodSchema
    ).optional(),
    fourHundredApplicationJsonObject: z.lazy(() =>
      GetMetaEventBadRequestResponseBody$zodSchema
    ).optional(),
    twoHundredApplicationJsonObject: z.lazy(() =>
      GetMetaEventResponseBody$zodSchema
    ).optional(),
  });
