/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  PortalLinkResponse,
  PortalLinkResponse$zodSchema,
} from "./portallinkresponse.js";

export type GetPortalLinkRequest = { projectID: string; portalLinkID: string };

export const GetPortalLinkRequest$zodSchema: z.ZodType<GetPortalLinkRequest> = z
  .object({
    portalLinkID: z.string().describe("portal link id"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type GetPortalLinkNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetPortalLinkNotFoundResponseBody$zodSchema: z.ZodType<
  GetPortalLinkNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetPortalLinkUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetPortalLinkUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetPortalLinkUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetPortalLinkBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetPortalLinkBadRequestResponseBody$zodSchema: z.ZodType<
  GetPortalLinkBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetPortalLinkResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: PortalLinkResponse | undefined;
};

export const GetPortalLinkResponseBody$zodSchema: z.ZodType<
  GetPortalLinkResponseBody
> = z.object({
  data: PortalLinkResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetPortalLinkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetPortalLinkResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetPortalLinkBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetPortalLinkUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetPortalLinkNotFoundResponseBody
    | undefined;
};

export const GetPortalLinkResponse$zodSchema: z.ZodType<GetPortalLinkResponse> =
  z.object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      GetPortalLinkNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      GetPortalLinkUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      GetPortalLinkBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      GetPortalLinkResponseBody$zodSchema
    ).optional().describe("OK"),
  });
