/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export const GetSubscriptionsDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type GetSubscriptionsDirection = ClosedEnum<
  typeof GetSubscriptionsDirection
>;

export const GetSubscriptionsDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type GetSubscriptionsRequest = {
  projectID: string;
  direction?: GetSubscriptionsDirection | undefined;
  endpointId?: Array<string> | undefined;
  name?: string | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  sort?: string | undefined;
};

export const GetSubscriptionsRequest$zodSchema: z.ZodType<
  GetSubscriptionsRequest
> = z.object({
  direction: GetSubscriptionsDirection$zodSchema.optional(),
  endpointId: z.array(z.string()).describe("A list of endpointIDs to filter by")
    .optional(),
  name: z.string().describe("Subscription name to filter by").optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  perPage: z.int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
});

/**
 * Not Found
 */
export type GetSubscriptionsNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionsNotFoundResponseBody$zodSchema: z.ZodType<
  GetSubscriptionsNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetSubscriptionsUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionsUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetSubscriptionsUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetSubscriptionsBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionsBadRequestResponseBody$zodSchema: z.ZodType<
  GetSubscriptionsBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type GetSubscriptionsData = {
  content?: Array<SubscriptionResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const GetSubscriptionsData$zodSchema: z.ZodType<GetSubscriptionsData> = z
  .object({
    content: z.array(SubscriptionResponse$zodSchema).optional(),
    pagination: PaginationData$zodSchema.optional(),
  });

/**
 * OK
 */
export type GetSubscriptionsResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: GetSubscriptionsData | undefined;
};

export const GetSubscriptionsResponseBody$zodSchema: z.ZodType<
  GetSubscriptionsResponseBody
> = z.object({
  data: z.lazy(() => GetSubscriptionsData$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetSubscriptionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetSubscriptionsResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetSubscriptionsBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetSubscriptionsUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetSubscriptionsNotFoundResponseBody
    | undefined;
};

export const GetSubscriptionsResponse$zodSchema: z.ZodType<
  GetSubscriptionsResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetSubscriptionsNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetSubscriptionsUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetSubscriptionsBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetSubscriptionsResponseBody$zodSchema
  ).optional().describe("OK"),
});
