/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type GetSubscriptionRequest = {
  projectID: string;
  subscriptionID: string;
};

export const GetSubscriptionRequest$zodSchema: z.ZodType<
  GetSubscriptionRequest
> = z.object({
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("subscription id"),
});

/**
 * Not Found
 */
export type GetSubscriptionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionNotFoundResponseBody$zodSchema: z.ZodType<
  GetSubscriptionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetSubscriptionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetSubscriptionUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetSubscriptionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSubscriptionBadRequestResponseBody$zodSchema: z.ZodType<
  GetSubscriptionBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetSubscriptionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: SubscriptionResponse | undefined;
};

export const GetSubscriptionResponseBody$zodSchema: z.ZodType<
  GetSubscriptionResponseBody
> = z.object({
  data: SubscriptionResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type GetSubscriptionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetSubscriptionResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetSubscriptionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetSubscriptionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetSubscriptionNotFoundResponseBody
    | undefined;
};

export const GetSubscriptionResponse$zodSchema: z.ZodType<
  GetSubscriptionResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetSubscriptionNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    GetSubscriptionUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    GetSubscriptionBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    GetSubscriptionResponseBody$zodSchema
  ).optional().describe("OK"),
});
