/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { SourceResponse, SourceResponse$zodSchema } from "./sourceresponse.js";

export type GetSourceRequest = { projectID: string; sourceID: string };

export const GetSourceRequest$zodSchema: z.ZodType<GetSourceRequest> = z.object(
  {
    projectID: z.string().describe("Project ID"),
    sourceID: z.string().describe("Source ID"),
  },
);

/**
 * Not Found
 */
export type GetSourceNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSourceNotFoundResponseBody$zodSchema: z.ZodType<
  GetSourceNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type GetSourceUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSourceUnauthorizedResponseBody$zodSchema: z.ZodType<
  GetSourceUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type GetSourceBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const GetSourceBadRequestResponseBody$zodSchema: z.ZodType<
  GetSourceBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type GetSourceResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: SourceResponse | undefined;
};

export const GetSourceResponseBody$zodSchema: z.ZodType<GetSourceResponseBody> =
  z.object({
    data: SourceResponse$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("OK");

export type GetSourceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: GetSourceResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | GetSourceBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | GetSourceUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetSourceNotFoundResponseBody
    | undefined;
};

export const GetSourceResponse$zodSchema: z.ZodType<GetSourceResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      GetSourceNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      GetSourceUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      GetSourceBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredApplicationJsonObject: z.lazy(() =>
      GetSourceResponseBody$zodSchema
    ).optional().describe("OK"),
  });
