/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GooglePubSubConfig = {
  project_id?: string | undefined;
  service_account?: Array<number> | undefined;
  subscription_id?: string | undefined;
};

export const GooglePubSubConfig$zodSchema: z.ZodType<GooglePubSubConfig> = z
  .object({
    project_id: z.string().optional(),
    service_account: z.array(z.int()).optional(),
    subscription_id: z.string().optional(),
  });
