/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EncodingType, EncodingType$zodSchema } from "./encodingtype.js";

export type HMac = {
  encoding: EncodingType;
  hash: string;
  header: string;
  secret: string;
};

export const HMac$zodSchema: z.ZodType<HMac> = z.object({
  encoding: EncodingType$zodSchema,
  hash: z.string(),
  header: z.string(),
  secret: z.string(),
});
