/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EventTypeResponse,
  EventTypeResponse$zodSchema,
} from "./eventtyperesponse.js";
import {
  ImportOpenAPISpec,
  ImportOpenAPISpec$zodSchema,
} from "./importopenapispec.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ImportOpenApiSpecRequest = {
  projectID: string;
  ImportOpenAPISpec: ImportOpenAPISpec;
};

export const ImportOpenApiSpecRequest$zodSchema: z.ZodType<
  ImportOpenApiSpecRequest
> = z.object({
  ImportOpenAPISpec: ImportOpenAPISpec$zodSchema,
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type ImportOpenApiSpecNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ImportOpenApiSpecNotFoundResponseBody$zodSchema: z.ZodType<
  ImportOpenApiSpecNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type ImportOpenApiSpecUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ImportOpenApiSpecUnauthorizedResponseBody$zodSchema: z.ZodType<
  ImportOpenApiSpecUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type ImportOpenApiSpecBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ImportOpenApiSpecBadRequestResponseBody$zodSchema: z.ZodType<
  ImportOpenApiSpecBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type ImportOpenApiSpecResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: Array<EventTypeResponse> | undefined;
};

export const ImportOpenApiSpecResponseBody$zodSchema: z.ZodType<
  ImportOpenApiSpecResponseBody
> = z.object({
  data: z.array(EventTypeResponse$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type ImportOpenApiSpecResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: ImportOpenApiSpecResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | ImportOpenApiSpecBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ImportOpenApiSpecUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ImportOpenApiSpecNotFoundResponseBody
    | undefined;
};

export const ImportOpenApiSpecResponse$zodSchema: z.ZodType<
  ImportOpenApiSpecResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    ImportOpenApiSpecNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ImportOpenApiSpecUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    ImportOpenApiSpecBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    ImportOpenApiSpecResponseBody$zodSchema
  ).optional(),
});
