/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type KafkaAuth = {
  hash?: string | undefined;
  password?: string | undefined;
  tls?: boolean | undefined;
  type?: string | undefined;
  username?: string | undefined;
};

export const KafkaAuth$zodSchema: z.ZodType<KafkaAuth> = z.object({
  hash: z.string().optional(),
  password: z.string().optional(),
  tls: z.boolean().optional(),
  type: z.string().optional(),
  username: z.string().optional(),
});
