/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { KafkaAuth, KafkaAuth$zodSchema } from "./kafkaauth.js";

export type KafkaPubSubConfig = {
  auth?: KafkaAuth | undefined;
  brokers?: Array<string> | undefined;
  consumer_group_id?: string | undefined;
  topic_name?: string | undefined;
};

export const KafkaPubSubConfig$zodSchema: z.ZodType<KafkaPubSubConfig> = z
  .object({
    auth: KafkaAuth$zodSchema.optional(),
    brokers: z.array(z.string()).optional(),
    consumer_group_id: z.string().optional(),
    topic_name: z.string().optional(),
  });
