/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";
import { SourceResponse, SourceResponse$zodSchema } from "./sourceresponse.js";

export const LoadSourcesPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type LoadSourcesPagedDirection = ClosedEnum<
  typeof LoadSourcesPagedDirection
>;

export const LoadSourcesPagedDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type LoadSourcesPagedRequest = {
  projectID: string;
  direction?: LoadSourcesPagedDirection | undefined;
  next_page_cursor?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  provider?: string | undefined;
  sort?: string | undefined;
  type?: string | undefined;
};

export const LoadSourcesPagedRequest$zodSchema: z.ZodType<
  LoadSourcesPagedRequest
> = z.object({
  direction: LoadSourcesPagedDirection$zodSchema.optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  perPage: z.int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  provider: z.string().describe(
    "The custom source provider e.g. twitter, shopify",
  ).optional(),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
  type: z.string().describe("The source type e.g. http, pub_sub").optional(),
});

/**
 * Not Found
 */
export type LoadSourcesPagedNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadSourcesPagedNotFoundResponseBody$zodSchema: z.ZodType<
  LoadSourcesPagedNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type LoadSourcesPagedUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadSourcesPagedUnauthorizedResponseBody$zodSchema: z.ZodType<
  LoadSourcesPagedUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type LoadSourcesPagedBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadSourcesPagedBadRequestResponseBody$zodSchema: z.ZodType<
  LoadSourcesPagedBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type LoadSourcesPagedData = {
  content?: Array<SourceResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const LoadSourcesPagedData$zodSchema: z.ZodType<LoadSourcesPagedData> = z
  .object({
    content: z.array(SourceResponse$zodSchema).optional(),
    pagination: PaginationData$zodSchema.optional(),
  });

/**
 * OK
 */
export type LoadSourcesPagedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: LoadSourcesPagedData | undefined;
};

export const LoadSourcesPagedResponseBody$zodSchema: z.ZodType<
  LoadSourcesPagedResponseBody
> = z.object({
  data: z.lazy(() => LoadSourcesPagedData$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type LoadSourcesPagedResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: LoadSourcesPagedResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | LoadSourcesPagedBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | LoadSourcesPagedUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | LoadSourcesPagedNotFoundResponseBody
    | undefined;
};

export const LoadSourcesPagedResponse$zodSchema: z.ZodType<
  LoadSourcesPagedResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    LoadSourcesPagedNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    LoadSourcesPagedUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    LoadSourcesPagedBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    LoadSourcesPagedResponseBody$zodSchema
  ).optional(),
});
