/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PaginationData, PaginationData$zodSchema } from "./paginationdata.js";
import {
  PortalLinkResponse,
  PortalLinkResponse$zodSchema,
} from "./portallinkresponse.js";

export const LoadPortalLinksPagedDirection = {
  Next: "next",
  Prev: "prev",
} as const;
export type LoadPortalLinksPagedDirection = ClosedEnum<
  typeof LoadPortalLinksPagedDirection
>;

export const LoadPortalLinksPagedDirection$zodSchema = z.enum([
  "next",
  "prev",
]);

export type LoadPortalLinksPagedRequest = {
  projectID: string;
  direction?: LoadPortalLinksPagedDirection | undefined;
  next_page_cursor?: string | undefined;
  ownerId?: string | undefined;
  perPage?: number | undefined;
  prev_page_cursor?: string | undefined;
  q?: string | undefined;
  sort?: string | undefined;
};

export const LoadPortalLinksPagedRequest$zodSchema: z.ZodType<
  LoadPortalLinksPagedRequest
> = z.object({
  direction: LoadPortalLinksPagedDirection$zodSchema.optional(),
  next_page_cursor: z.string().describe(
    "A pagination cursor to fetch the next page of a list",
  ).optional(),
  ownerId: z.string().describe("The owner ID of the endpoint").optional(),
  perPage: z.int().describe("The number of items to return per page")
    .optional(),
  prev_page_cursor: z.string().describe(
    "A pagination cursor to fetch the previous page of a list",
  ).optional(),
  projectID: z.string().describe("Project ID"),
  q: z.string().describe("The name of the endpoint").optional(),
  sort: z.string().describe(
    "Sort order, values are `ASC` or `DESC`, defaults to `DESC`",
  ).optional(),
});

/**
 * Not Found
 */
export type LoadPortalLinksPagedNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadPortalLinksPagedNotFoundResponseBody$zodSchema: z.ZodType<
  LoadPortalLinksPagedNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type LoadPortalLinksPagedUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadPortalLinksPagedUnauthorizedResponseBody$zodSchema: z.ZodType<
  LoadPortalLinksPagedUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type LoadPortalLinksPagedBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const LoadPortalLinksPagedBadRequestResponseBody$zodSchema: z.ZodType<
  LoadPortalLinksPagedBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

export type LoadPortalLinksPagedData = {
  content?: Array<PortalLinkResponse> | undefined;
  pagination?: PaginationData | undefined;
};

export const LoadPortalLinksPagedData$zodSchema: z.ZodType<
  LoadPortalLinksPagedData
> = z.object({
  content: z.array(PortalLinkResponse$zodSchema).optional(),
  pagination: PaginationData$zodSchema.optional(),
});

/**
 * OK
 */
export type LoadPortalLinksPagedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: LoadPortalLinksPagedData | undefined;
};

export const LoadPortalLinksPagedResponseBody$zodSchema: z.ZodType<
  LoadPortalLinksPagedResponseBody
> = z.object({
  data: z.lazy(() => LoadPortalLinksPagedData$zodSchema).optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type LoadPortalLinksPagedResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | LoadPortalLinksPagedResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | LoadPortalLinksPagedBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | LoadPortalLinksPagedUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | LoadPortalLinksPagedNotFoundResponseBody
    | undefined;
};

export const LoadPortalLinksPagedResponse$zodSchema: z.ZodType<
  LoadPortalLinksPagedResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    LoadPortalLinksPagedNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    LoadPortalLinksPagedUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    LoadPortalLinksPagedBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    LoadPortalLinksPagedResponseBody$zodSchema
  ).optional(),
});
