/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  StrategyProvider,
  StrategyProvider$zodSchema,
} from "./strategyprovider.js";

export type Metadata = {
  data?: Array<number> | undefined;
  interval_seconds?: number | undefined;
  max_retry_seconds?: number | undefined;
  next_send_time?: string | undefined;
  num_trials?: number | undefined;
  raw?: string | undefined;
  retry_limit?: number | undefined;
  strategy?: StrategyProvider | undefined;
};

export const Metadata$zodSchema: z.ZodType<Metadata> = z.object({
  data: z.array(z.int()).optional().describe("Data to be sent to endpoint."),
  interval_seconds: z.int().optional(),
  max_retry_seconds: z.int().optional(),
  next_send_time: z.string().optional(),
  num_trials: z.int().optional().describe(
    "NumTrials: number of times we have tried to deliver this Event to\nan application",
  ),
  raw: z.string().optional(),
  retry_limit: z.int().optional(),
  strategy: StrategyProvider$zodSchema.optional(),
});
