/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MetaEventAttempt = {
  request_http_header?: { [k: string]: string } | undefined;
  response_data?: string | undefined;
  response_http_header?: { [k: string]: string } | undefined;
};

export const MetaEventAttempt$zodSchema: z.ZodType<MetaEventAttempt> = z.object(
  {
    request_http_header: z.record(z.string(), z.string()).optional(),
    response_data: z.string().optional(),
    response_http_header: z.record(z.string(), z.string()).optional(),
  },
);
