/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ObjectT = {};

export const ObjectT$zodSchema: z.ZodType<ObjectT, z.ZodTypeDef, unknown> = z
  .object({});
