/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PortalLink = {
  can_manage_endpoint?: boolean | undefined;
  endpoints?: Array<string> | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
};

export const PortalLink$zodSchema: z.ZodType<PortalLink> = z.object({
  can_manage_endpoint: z.boolean().optional(),
  endpoints: z.array(z.string()).optional(),
  name: z.string().optional(),
  owner_id: z.string().optional(),
});
