/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Endpoint, Endpoint$zodSchema } from "./endpoint.js";

export type PortalLinkResponse = {
  auth_key?: string | undefined;
  can_manage_endpoint?: boolean | undefined;
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  endpoint_count?: number | undefined;
  endpoints?: Array<string> | undefined;
  endpoints_metadata?: Array<Endpoint> | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
  project_id?: string | undefined;
  token?: string | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  url?: string | undefined;
};

export const PortalLinkResponse$zodSchema: z.ZodType<PortalLinkResponse> = z
  .object({
    auth_key: z.string().optional(),
    can_manage_endpoint: z.boolean().optional(),
    created_at: z.string().optional(),
    deleted_at: z.string().optional(),
    endpoint_count: z.int().optional(),
    endpoints: z.array(z.string()).optional(),
    endpoints_metadata: z.array(Endpoint$zodSchema).optional(),
    name: z.string().optional(),
    owner_id: z.string().optional(),
    project_id: z.string().optional(),
    token: z.string().optional(),
    uid: z.string().optional(),
    updated_at: z.string().optional(),
    url: z.string().optional(),
  });
