/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PortalLink = {
  can_manage_endpoint?: boolean | undefined;
  endpoints?: Array<string> | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
};

export const PortalLink$zodSchema: z.ZodType<PortalLink> = z.object({
  can_manage_endpoint: z.boolean().optional().describe(
    "Specify whether endpoint management can be done through the Portal Link UI",
  ),
  endpoints: z.array(z.string()).optional().describe(
    "IDs of endpoints in this portal link",
  ),
  name: z.string().optional().describe("Portal Link Name"),
  owner_id: z.string().optional().describe(
    "Alternatively specify OwnerID, the portal link will inherit all the endpoints with this owner ID",
  ),
});
