/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TwitterProviderConfig,
  TwitterProviderConfig$zodSchema,
} from "./twitterproviderconfig.js";

export type ProviderConfig = { twitter?: TwitterProviderConfig | undefined };

export const ProviderConfig$zodSchema: z.ZodType<ProviderConfig> = z.object({
  twitter: TwitterProviderConfig$zodSchema.optional(),
});
