/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AmqpPubSubconfig,
  AmqpPubSubconfig$zodSchema,
} from "./amqppubsubconfig.js";
import {
  GooglePubSubConfig,
  GooglePubSubConfig$zodSchema,
} from "./googlepubsubconfig.js";
import {
  KafkaPubSubConfig,
  KafkaPubSubConfig$zodSchema,
} from "./kafkapubsubconfig.js";
import { PubSubType, PubSubType$zodSchema } from "./pubsubtype.js";
import {
  SQSPubSubConfig,
  SQSPubSubConfig$zodSchema,
} from "./sqspubsubconfig.js";

export type PubSubConfig = {
  amqp?: AmqpPubSubconfig | undefined;
  google?: GooglePubSubConfig | undefined;
  kafka?: KafkaPubSubConfig | undefined;
  sqs?: SQSPubSubConfig | undefined;
  type?: PubSubType | undefined;
  workers?: number | undefined;
};

export const PubSubConfig$zodSchema: z.ZodType<PubSubConfig> = z.object({
  amqp: AmqpPubSubconfig$zodSchema.optional(),
  google: GooglePubSubConfig$zodSchema.optional(),
  kafka: KafkaPubSubConfig$zodSchema.optional(),
  sqs: SQSPubSubConfig$zodSchema.optional(),
  type: PubSubType$zodSchema.optional(),
  workers: z.int().optional(),
});
