/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RateLimitConfiguration = {
  count?: number | undefined;
  duration?: number | undefined;
};

export const RateLimitConfiguration$zodSchema: z.ZodType<
  RateLimitConfiguration
> = z.object({
  count: z.int().optional(),
  duration: z.int().optional(),
});
