/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type RefreshPortalLinkAuthTokenRequest = {
  projectID: string;
  portalLinkID: string;
};

export const RefreshPortalLinkAuthTokenRequest$zodSchema: z.ZodType<
  RefreshPortalLinkAuthTokenRequest
> = z.object({
  portalLinkID: z.string().describe("portal link id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type RefreshPortalLinkAuthTokenNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RefreshPortalLinkAuthTokenNotFoundResponseBody$zodSchema:
  z.ZodType<RefreshPortalLinkAuthTokenNotFoundResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Not Found");

/**
 * Unauthorized
 */
export type RefreshPortalLinkAuthTokenUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RefreshPortalLinkAuthTokenUnauthorizedResponseBody$zodSchema:
  z.ZodType<RefreshPortalLinkAuthTokenUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type RefreshPortalLinkAuthTokenBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RefreshPortalLinkAuthTokenBadRequestResponseBody$zodSchema:
  z.ZodType<RefreshPortalLinkAuthTokenBadRequestResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Bad Request");

/**
 * OK
 */
export type RefreshPortalLinkAuthTokenResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: string | undefined;
};

export const RefreshPortalLinkAuthTokenResponseBody$zodSchema: z.ZodType<
  RefreshPortalLinkAuthTokenResponseBody
> = z.object({
  data: z.string().optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type RefreshPortalLinkAuthTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | RefreshPortalLinkAuthTokenResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | RefreshPortalLinkAuthTokenBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | RefreshPortalLinkAuthTokenUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | RefreshPortalLinkAuthTokenNotFoundResponseBody
    | undefined;
};

export const RefreshPortalLinkAuthTokenResponse$zodSchema: z.ZodType<
  RefreshPortalLinkAuthTokenResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    RefreshPortalLinkAuthTokenNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    RefreshPortalLinkAuthTokenUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    RefreshPortalLinkAuthTokenBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    RefreshPortalLinkAuthTokenResponseBody$zodSchema
  ).optional().describe("OK"),
});
