/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EventResponse, EventResponse$zodSchema } from "./eventresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ReplayEndpointEventRequest = { projectID: string; eventID: string };

export const ReplayEndpointEventRequest$zodSchema: z.ZodType<
  ReplayEndpointEventRequest
> = z.object({
  eventID: z.string().describe("event id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type ReplayEndpointEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ReplayEndpointEventNotFoundResponseBody$zodSchema: z.ZodType<
  ReplayEndpointEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type ReplayEndpointEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ReplayEndpointEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  ReplayEndpointEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type ReplayEndpointEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ReplayEndpointEventBadRequestResponseBody$zodSchema: z.ZodType<
  ReplayEndpointEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type ReplayEndpointEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EventResponse | undefined;
};

export const ReplayEndpointEventResponseBody$zodSchema: z.ZodType<
  ReplayEndpointEventResponseBody
> = z.object({
  data: EventResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type ReplayEndpointEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: ReplayEndpointEventResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | ReplayEndpointEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ReplayEndpointEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ReplayEndpointEventNotFoundResponseBody
    | undefined;
};

export const ReplayEndpointEventResponse$zodSchema: z.ZodType<
  ReplayEndpointEventResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    ReplayEndpointEventNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ReplayEndpointEventUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    ReplayEndpointEventBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    ReplayEndpointEventResponseBody$zodSchema
  ).optional(),
});
