/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MetaEventResponse,
  MetaEventResponse$zodSchema,
} from "./metaeventresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type ResendMetaEventRequest = { projectID: string; metaEventID: string };

export const ResendMetaEventRequest$zodSchema: z.ZodType<
  ResendMetaEventRequest
> = z.object({
  metaEventID: z.string().describe("meta event id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type ResendMetaEventNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ResendMetaEventNotFoundResponseBody$zodSchema: z.ZodType<
  ResendMetaEventNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type ResendMetaEventUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ResendMetaEventUnauthorizedResponseBody$zodSchema: z.ZodType<
  ResendMetaEventUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type ResendMetaEventBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const ResendMetaEventBadRequestResponseBody$zodSchema: z.ZodType<
  ResendMetaEventBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type ResendMetaEventResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: MetaEventResponse | undefined;
};

export const ResendMetaEventResponseBody$zodSchema: z.ZodType<
  ResendMetaEventResponseBody
> = z.object({
  data: MetaEventResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type ResendMetaEventResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: ResendMetaEventResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | ResendMetaEventBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | ResendMetaEventUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | ResendMetaEventNotFoundResponseBody
    | undefined;
};

export const ResendMetaEventResponse$zodSchema: z.ZodType<
  ResendMetaEventResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    ResendMetaEventNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    ResendMetaEventUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    ResendMetaEventBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    ResendMetaEventResponseBody$zodSchema
  ).optional().describe("OK"),
});
