/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  StrategyProvider,
  StrategyProvider$zodSchema,
} from "./strategyprovider.js";

export type RetryConfiguration = {
  duration?: string | undefined;
  interval_seconds?: number | undefined;
  retry_count?: number | undefined;
  type?: StrategyProvider | undefined;
};

export const RetryConfiguration$zodSchema: z.ZodType<RetryConfiguration> = z
  .object({
    duration: z.string().optional().describe(
      "Used to specify a valid Go time duration e.g 10s, 1h3m for how long to wait between event delivery retries",
    ),
    interval_seconds: z.int().optional().describe(
      "Used to specify a time in seconds for how long to wait between event delivery retries,",
    ),
    retry_count: z.int().optional().describe(
      "Used to specify the max number of retries",
    ),
    type: StrategyProvider$zodSchema.optional().describe("Retry Strategy type"),
  });
