/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  StrategyProvider,
  StrategyProvider$zodSchema,
} from "./strategyprovider.js";

export type RetryConfiguration = {
  duration?: string | undefined;
  interval_seconds?: number | undefined;
  retry_count?: number | undefined;
  type?: StrategyProvider | undefined;
};

export const RetryConfiguration$zodSchema: z.ZodType<RetryConfiguration> = z
  .object({
    duration: z.string().optional(),
    interval_seconds: z.int().optional(),
    retry_count: z.int().optional(),
    type: StrategyProvider$zodSchema.optional(),
  });
