/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type RevokePortalLinkRequest = {
  projectID: string;
  portalLinkID: string;
};

export const RevokePortalLinkRequest$zodSchema: z.ZodType<
  RevokePortalLinkRequest
> = z.object({
  portalLinkID: z.string().describe("portal link id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type RevokePortalLinkNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RevokePortalLinkNotFoundResponseBody$zodSchema: z.ZodType<
  RevokePortalLinkNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type RevokePortalLinkUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RevokePortalLinkUnauthorizedResponseBody$zodSchema: z.ZodType<
  RevokePortalLinkUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type RevokePortalLinkBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RevokePortalLinkBadRequestResponseBody$zodSchema: z.ZodType<
  RevokePortalLinkBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type RevokePortalLinkResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const RevokePortalLinkResponseBody$zodSchema: z.ZodType<
  RevokePortalLinkResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type RevokePortalLinkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: RevokePortalLinkResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | RevokePortalLinkBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | RevokePortalLinkUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | RevokePortalLinkNotFoundResponseBody
    | undefined;
};

export const RevokePortalLinkResponse$zodSchema: z.ZodType<
  RevokePortalLinkResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    RevokePortalLinkNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    RevokePortalLinkUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    RevokePortalLinkBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    RevokePortalLinkResponseBody$zodSchema
  ).optional().describe("OK"),
});
