/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Secret = {
  created_at?: string | undefined;
  deleted_at?: string | undefined;
  expires_at?: string | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  value?: string | undefined;
};

export const Secret$zodSchema: z.ZodType<Secret> = z.object({
  created_at: z.string().optional(),
  deleted_at: z.string().optional(),
  expires_at: z.string().optional(),
  uid: z.string().optional(),
  updated_at: z.string().optional(),
  value: z.string().optional(),
});
