/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CustomResponse, CustomResponse$zodSchema } from "./customresponse.js";
import { ProviderConfig, ProviderConfig$zodSchema } from "./providerconfig.js";
import { PubSubConfig, PubSubConfig$zodSchema } from "./pubsubconfig.js";
import { SourceProvider, SourceProvider$zodSchema } from "./sourceprovider.js";
import { SourceType, SourceType$zodSchema } from "./sourcetype.js";
import { VerifierConfig, VerifierConfig$zodSchema } from "./verifierconfig.js";

export type SourceResponse = {
  body_function?: string | undefined;
  created_at?: string | undefined;
  custom_response?: CustomResponse | undefined;
  deleted_at?: string | undefined;
  forward_headers?: Array<string> | undefined;
  header_function?: string | undefined;
  idempotency_keys?: Array<string> | undefined;
  is_disabled?: boolean | undefined;
  mask_id?: string | undefined;
  name?: string | undefined;
  project_id?: string | undefined;
  provider?: SourceProvider | undefined;
  provider_config?: ProviderConfig | undefined;
  pub_sub?: PubSubConfig | undefined;
  type?: SourceType | undefined;
  uid?: string | undefined;
  updated_at?: string | undefined;
  url?: string | undefined;
  verifier?: VerifierConfig | undefined;
};

export const SourceResponse$zodSchema: z.ZodType<SourceResponse> = z.object({
  body_function: z.string().optional(),
  created_at: z.string().optional(),
  custom_response: CustomResponse$zodSchema.optional(),
  deleted_at: z.string().optional(),
  forward_headers: z.array(z.string()).optional(),
  header_function: z.string().optional(),
  idempotency_keys: z.array(z.string()).optional(),
  is_disabled: z.boolean().optional(),
  mask_id: z.string().optional(),
  name: z.string().optional(),
  project_id: z.string().optional(),
  provider: SourceProvider$zodSchema.optional(),
  provider_config: ProviderConfig$zodSchema.optional(),
  pub_sub: PubSubConfig$zodSchema.optional(),
  type: SourceType$zodSchema.optional(),
  uid: z.string().optional(),
  updated_at: z.string().optional(),
  url: z.string().optional(),
  verifier: VerifierConfig$zodSchema.optional(),
});
