/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SourceProvider = {
  Github: "github",
  Twitter: "twitter",
  Shopify: "shopify",
} as const;
export type SourceProvider = ClosedEnum<typeof SourceProvider>;

export const SourceProvider$zodSchema = z.enum([
  "github",
  "twitter",
  "shopify",
]);
