/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SourceType = {
  Http: "http",
  RestApi: "rest_api",
  PubSub: "pub_sub",
  DbChangeStream: "db_change_stream",
} as const;
export type SourceType = ClosedEnum<typeof SourceType>;

export const SourceType$zodSchema = z.enum([
  "http",
  "rest_api",
  "pub_sub",
  "db_change_stream",
]);
