/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SQSPubSubConfig = {
  access_key_id?: string | undefined;
  default_region?: string | undefined;
  queue_name?: string | undefined;
  secret_key?: string | undefined;
};

export const SQSPubSubConfig$zodSchema: z.ZodType<SQSPubSubConfig> = z.object({
  access_key_id: z.string().optional(),
  default_region: z.string().optional(),
  queue_name: z.string().optional(),
  secret_key: z.string().optional(),
});
