/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const StrategyProvider = {
  Linear: "linear",
  Exponential: "exponential",
} as const;
export type StrategyProvider = ClosedEnum<typeof StrategyProvider>;

export const StrategyProvider$zodSchema = z.enum([
  "linear",
  "exponential",
]);
