/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionType = {
  Cli: "cli",
  Api: "api",
} as const;
export type SubscriptionType = ClosedEnum<typeof SubscriptionType>;

export const SubscriptionType$zodSchema = z.enum([
  "cli",
  "api",
]);
