/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FunctionRequest,
  FunctionRequest$zodSchema,
} from "./functionrequest.js";
import {
  FunctionResponse,
  FunctionResponse$zodSchema,
} from "./functionresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type TestSubscriptionFunctionRequest = {
  projectID: string;
  FunctionRequest: FunctionRequest;
};

export const TestSubscriptionFunctionRequest$zodSchema: z.ZodType<
  TestSubscriptionFunctionRequest
> = z.object({
  FunctionRequest: FunctionRequest$zodSchema.describe("Function Details"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type TestSubscriptionFunctionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFunctionNotFoundResponseBody$zodSchema: z.ZodType<
  TestSubscriptionFunctionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type TestSubscriptionFunctionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFunctionUnauthorizedResponseBody$zodSchema:
  z.ZodType<TestSubscriptionFunctionUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type TestSubscriptionFunctionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFunctionBadRequestResponseBody$zodSchema:
  z.ZodType<TestSubscriptionFunctionBadRequestResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Bad Request");

/**
 * OK
 */
export type TestSubscriptionFunctionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: FunctionResponse | undefined;
};

export const TestSubscriptionFunctionResponseBody$zodSchema: z.ZodType<
  TestSubscriptionFunctionResponseBody
> = z.object({
  data: FunctionResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type TestSubscriptionFunctionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | TestSubscriptionFunctionResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | TestSubscriptionFunctionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | TestSubscriptionFunctionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | TestSubscriptionFunctionNotFoundResponseBody
    | undefined;
};

export const TestSubscriptionFunctionResponse$zodSchema: z.ZodType<
  TestSubscriptionFunctionResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFunctionNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFunctionUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFunctionBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFunctionResponseBody$zodSchema
  ).optional().describe("OK"),
});
