/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilterSchema, FilterSchema$zodSchema } from "./filterschema.js";

export type TestFilter = {
  request?: FilterSchema | undefined;
  schema?: FilterSchema | undefined;
};

export const TestFilter$zodSchema: z.ZodType<TestFilter> = z.object({
  request: FilterSchema$zodSchema.optional(),
  schema: FilterSchema$zodSchema.optional(),
});
