/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { TestFilter, TestFilter$zodSchema } from "./testfilter.js";

export type TestSubscriptionFilterRequest = {
  projectID: string;
  TestFilter: TestFilter;
};

export const TestSubscriptionFilterRequest$zodSchema: z.ZodType<
  TestSubscriptionFilterRequest
> = z.object({
  TestFilter: TestFilter$zodSchema,
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type TestSubscriptionFilterNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFilterNotFoundResponseBody$zodSchema: z.ZodType<
  TestSubscriptionFilterNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type TestSubscriptionFilterUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFilterUnauthorizedResponseBody$zodSchema:
  z.ZodType<TestSubscriptionFilterUnauthorizedResponseBody> = z.object({
    data: ObjectT$zodSchema.optional(),
    message: z.string().optional(),
    status: z.boolean().optional(),
  }).describe("Unauthorized");

/**
 * Bad Request
 */
export type TestSubscriptionFilterBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSubscriptionFilterBadRequestResponseBody$zodSchema: z.ZodType<
  TestSubscriptionFilterBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type TestSubscriptionFilterResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: boolean | undefined;
};

export const TestSubscriptionFilterResponseBody$zodSchema: z.ZodType<
  TestSubscriptionFilterResponseBody
> = z.object({
  data: z.boolean().optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type TestSubscriptionFilterResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?:
    | TestSubscriptionFilterResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | TestSubscriptionFilterBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | TestSubscriptionFilterUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | TestSubscriptionFilterNotFoundResponseBody
    | undefined;
};

export const TestSubscriptionFilterResponse$zodSchema: z.ZodType<
  TestSubscriptionFilterResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFilterNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFilterUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFilterBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    TestSubscriptionFilterResponseBody$zodSchema
  ).optional(),
});
