/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FunctionRequest,
  FunctionRequest$zodSchema,
} from "./functionrequest.js";
import {
  FunctionResponse,
  FunctionResponse$zodSchema,
} from "./functionresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";

export type TestSourceFunctionRequest = {
  projectID: string;
  FunctionRequest: FunctionRequest;
};

export const TestSourceFunctionRequest$zodSchema: z.ZodType<
  TestSourceFunctionRequest
> = z.object({
  FunctionRequest: FunctionRequest$zodSchema,
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type TestSourceFunctionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSourceFunctionNotFoundResponseBody$zodSchema: z.ZodType<
  TestSourceFunctionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type TestSourceFunctionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSourceFunctionUnauthorizedResponseBody$zodSchema: z.ZodType<
  TestSourceFunctionUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type TestSourceFunctionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const TestSourceFunctionBadRequestResponseBody$zodSchema: z.ZodType<
  TestSourceFunctionBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type TestSourceFunctionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: FunctionResponse | undefined;
};

export const TestSourceFunctionResponseBody$zodSchema: z.ZodType<
  TestSourceFunctionResponseBody
> = z.object({
  data: FunctionResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type TestSourceFunctionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: TestSourceFunctionResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | TestSourceFunctionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | TestSourceFunctionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | TestSourceFunctionNotFoundResponseBody
    | undefined;
};

export const TestSourceFunctionResponse$zodSchema: z.ZodType<
  TestSourceFunctionResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    TestSourceFunctionNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    TestSourceFunctionUnauthorizedResponseBody$zodSchema
  ).optional(),
  fourHundredApplicationJsonObject: z.lazy(() =>
    TestSourceFunctionBadRequestResponseBody$zodSchema
  ).optional(),
  twoHundredApplicationJsonObject: z.lazy(() =>
    TestSourceFunctionResponseBody$zodSchema
  ).optional(),
});
