/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TestFilterResponse = { is_match?: boolean | undefined };

export const TestFilterResponse$zodSchema: z.ZodType<TestFilterResponse> = z
  .object({
    is_match: z.boolean().optional(),
  });
