/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TestFilterRequest = { payload?: any | undefined };

export const TestFilterRequest$zodSchema: z.ZodType<TestFilterRequest> = z
  .object({
    payload: z.any().optional().describe(
      "Sample payload to test against the filter (required)",
    ),
  });
