/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TwitterProviderConfig = { crc_verified_at?: string | undefined };

export const TwitterProviderConfig$zodSchema: z.ZodType<TwitterProviderConfig> =
  z.object({
    crc_verified_at: z.string().optional(),
  });
