/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilterResponse, FilterResponse$zodSchema } from "./filterresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  UpdateFilterRequest,
  UpdateFilterRequest$zodSchema,
} from "./updatefilterrequest.js";

export type UpdateFilterRequestRequest = {
  projectID: string;
  subscriptionID: string;
  filterID: string;
  UpdateFilterRequest: UpdateFilterRequest;
};

export const UpdateFilterRequestRequest$zodSchema: z.ZodType<
  UpdateFilterRequestRequest
> = z.object({
  UpdateFilterRequest: UpdateFilterRequest$zodSchema,
  filterID: z.string().describe("Filter ID"),
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("Subscription ID"),
});

/**
 * Not Found
 */
export type UpdateFilterNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateFilterNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateFilterNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdateFilterUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateFilterUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdateFilterUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdateFilterBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateFilterBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateFilterBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * OK
 */
export type UpdateFilterResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: FilterResponse | undefined;
};

export const UpdateFilterResponseBody$zodSchema: z.ZodType<
  UpdateFilterResponseBody
> = z.object({
  data: FilterResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("OK");

export type UpdateFilterResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredApplicationJsonObject?: UpdateFilterResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | UpdateFilterBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdateFilterUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdateFilterNotFoundResponseBody
    | undefined;
};

export const UpdateFilterResponse$zodSchema: z.ZodType<UpdateFilterResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      UpdateFilterNotFoundResponseBody$zodSchema
    ).optional(),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      UpdateFilterUnauthorizedResponseBody$zodSchema
    ).optional(),
    fourHundredApplicationJsonObject: z.lazy(() =>
      UpdateFilterBadRequestResponseBody$zodSchema
    ).optional(),
    twoHundredApplicationJsonObject: z.lazy(() =>
      UpdateFilterResponseBody$zodSchema
    ).optional(),
  });
