/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { SourceResponse, SourceResponse$zodSchema } from "./sourceresponse.js";
import { UpdateSource, UpdateSource$zodSchema } from "./updatesource.js";

export type UpdateSourceRequest = {
  projectID: string;
  sourceID: string;
  UpdateSource: UpdateSource;
};

export const UpdateSourceRequest$zodSchema: z.ZodType<UpdateSourceRequest> = z
  .object({
    UpdateSource: UpdateSource$zodSchema.describe("Source Details"),
    projectID: z.string().describe("Project ID"),
    sourceID: z.string().describe("source id"),
  });

/**
 * Not Found
 */
export type UpdateSourceNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSourceNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateSourceNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdateSourceUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSourceUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdateSourceUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdateSourceBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSourceBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateSourceBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Accepted
 */
export type UpdateSourceResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: SourceResponse | undefined;
};

export const UpdateSourceResponseBody$zodSchema: z.ZodType<
  UpdateSourceResponseBody
> = z.object({
  data: SourceResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Accepted");

export type UpdateSourceResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndTwoApplicationJsonObject?: UpdateSourceResponseBody | undefined;
  fourHundredApplicationJsonObject?:
    | UpdateSourceBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdateSourceUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdateSourceNotFoundResponseBody
    | undefined;
};

export const UpdateSourceResponse$zodSchema: z.ZodType<UpdateSourceResponse> = z
  .object({
    ContentType: z.string().describe(
      "HTTP response content type for this operation",
    ),
    RawResponse: z.custom<Response>(x => x instanceof Response).describe(
      "Raw HTTP response; suitable for custom response parsing",
    ),
    StatusCode: z.int().describe(
      "HTTP response status code for this operation",
    ),
    fourHundredAndFourApplicationJsonObject: z.lazy(() =>
      UpdateSourceNotFoundResponseBody$zodSchema
    ).optional().describe("Not Found"),
    fourHundredAndOneApplicationJsonObject: z.lazy(() =>
      UpdateSourceUnauthorizedResponseBody$zodSchema
    ).optional().describe("Unauthorized"),
    fourHundredApplicationJsonObject: z.lazy(() =>
      UpdateSourceBadRequestResponseBody$zodSchema
    ).optional().describe("Bad Request"),
    twoHundredAndTwoApplicationJsonObject: z.lazy(() =>
      UpdateSourceResponseBody$zodSchema
    ).optional().describe("Accepted"),
  });
