/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PubSubConfig, PubSubConfig$zodSchema } from "./pubsubconfig.js";
import { SourceType, SourceType$zodSchema } from "./sourcetype.js";
import {
  UpdateCustomResponse,
  UpdateCustomResponse$zodSchema,
} from "./updatecustomresponse.js";
import { VerifierConfig, VerifierConfig$zodSchema } from "./verifierconfig.js";

export type UpdateSource = {
  body_function?: string | undefined;
  custom_response?: UpdateCustomResponse | undefined;
  forward_headers?: Array<string> | undefined;
  header_function?: string | undefined;
  idempotency_keys?: Array<string> | undefined;
  is_disabled?: boolean | undefined;
  name?: string | undefined;
  pub_sub?: PubSubConfig | undefined;
  type?: SourceType | undefined;
  verifier?: VerifierConfig | undefined;
};

export const UpdateSource$zodSchema: z.ZodType<UpdateSource> = z.object({
  body_function: z.string().optional(),
  custom_response: UpdateCustomResponse$zodSchema.optional(),
  forward_headers: z.array(z.string()).optional(),
  header_function: z.string().optional(),
  idempotency_keys: z.array(z.string()).optional(),
  is_disabled: z.boolean().optional(),
  name: z.string().optional(),
  pub_sub: PubSubConfig$zodSchema.optional(),
  type: SourceType$zodSchema.optional(),
  verifier: VerifierConfig$zodSchema.optional(),
});
