/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateFilterRequest = {
  body?: { [k: string]: any } | undefined;
  event_type?: string | undefined;
  headers?: { [k: string]: any } | undefined;
  is_flattened?: boolean | undefined;
};

export const UpdateFilterRequest$zodSchema: z.ZodType<UpdateFilterRequest> = z
  .object({
    body: z.record(z.string(), z.any()).optional(),
    event_type: z.string().optional(),
    headers: z.record(z.string(), z.any()).optional(),
    is_flattened: z.boolean().optional(),
  });
