/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";
import {
  UpdateSubscription,
  UpdateSubscription$zodSchema,
} from "./updatesubscription.js";

export type UpdateSubscriptionRequest = {
  projectID: string;
  subscriptionID: string;
  UpdateSubscription: UpdateSubscription;
};

export const UpdateSubscriptionRequest$zodSchema: z.ZodType<
  UpdateSubscriptionRequest
> = z.object({
  UpdateSubscription: UpdateSubscription$zodSchema.describe(
    "Subscription Details",
  ),
  projectID: z.string().describe("Project ID"),
  subscriptionID: z.string().describe("subscription id"),
});

/**
 * Not Found
 */
export type UpdateSubscriptionNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSubscriptionNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateSubscriptionNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdateSubscriptionUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSubscriptionUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdateSubscriptionUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdateSubscriptionBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateSubscriptionBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateSubscriptionBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Accepted
 */
export type UpdateSubscriptionResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: SubscriptionResponse | undefined;
};

export const UpdateSubscriptionResponseBody$zodSchema: z.ZodType<
  UpdateSubscriptionResponseBody
> = z.object({
  data: SubscriptionResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Accepted");

export type UpdateSubscriptionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndTwoApplicationJsonObject?:
    | UpdateSubscriptionResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | UpdateSubscriptionBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdateSubscriptionUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdateSubscriptionNotFoundResponseBody
    | undefined;
};

export const UpdateSubscriptionResponse$zodSchema: z.ZodType<
  UpdateSubscriptionResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    UpdateSubscriptionNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    UpdateSubscriptionUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    UpdateSubscriptionBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndTwoApplicationJsonObject: z.lazy(() =>
    UpdateSubscriptionResponseBody$zodSchema
  ).optional().describe("Accepted"),
});
