/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { PortalLink, PortalLink$zodSchema } from "./portallink.js";
import {
  PortalLinkResponse,
  PortalLinkResponse$zodSchema,
} from "./portallinkresponse.js";

export type UpdatePortalLinkRequest = {
  projectID: string;
  portalLinkID: string;
  PortalLink: PortalLink;
};

export const UpdatePortalLinkRequest$zodSchema: z.ZodType<
  UpdatePortalLinkRequest
> = z.object({
  PortalLink: PortalLink$zodSchema.describe("Portal Link Details"),
  portalLinkID: z.string().describe("portal link id"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type UpdatePortalLinkNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdatePortalLinkNotFoundResponseBody$zodSchema: z.ZodType<
  UpdatePortalLinkNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdatePortalLinkUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdatePortalLinkUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdatePortalLinkUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdatePortalLinkBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdatePortalLinkBadRequestResponseBody$zodSchema: z.ZodType<
  UpdatePortalLinkBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Accepted
 */
export type UpdatePortalLinkResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: PortalLinkResponse | undefined;
};

export const UpdatePortalLinkResponseBody$zodSchema: z.ZodType<
  UpdatePortalLinkResponseBody
> = z.object({
  data: PortalLinkResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Accepted");

export type UpdatePortalLinkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndTwoApplicationJsonObject?:
    | UpdatePortalLinkResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | UpdatePortalLinkBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdatePortalLinkUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdatePortalLinkNotFoundResponseBody
    | undefined;
};

export const UpdatePortalLinkResponse$zodSchema: z.ZodType<
  UpdatePortalLinkResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    UpdatePortalLinkNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    UpdatePortalLinkUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    UpdatePortalLinkBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndTwoApplicationJsonObject: z.lazy(() =>
    UpdatePortalLinkResponseBody$zodSchema
  ).optional().describe("Accepted"),
});
