/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  AlertConfiguration,
  AlertConfiguration$zodSchema,
} from "./alertconfiguration.js";
import {
  FilterConfiguration,
  FilterConfiguration$zodSchema,
} from "./filterconfiguration.js";
import {
  RateLimitConfiguration,
  RateLimitConfiguration$zodSchema,
} from "./ratelimitconfiguration.js";
import {
  RetryConfiguration,
  RetryConfiguration$zodSchema,
} from "./retryconfiguration.js";

/**
 * Delivery mode configuration
 */
export const UpdateSubscriptionDeliveryMode = {
  AtLeastOnce: "at_least_once",
  AtMostOnce: "at_most_once",
} as const;
/**
 * Delivery mode configuration
 */
export type UpdateSubscriptionDeliveryMode = OpenEnum<
  typeof UpdateSubscriptionDeliveryMode
>;

export const UpdateSubscriptionDeliveryMode$zodSchema = z.union([
  z.enum([
    "at_least_once",
    "at_most_once",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Delivery mode configuration");

export type UpdateSubscription = {
  alert_config?: AlertConfiguration | undefined;
  app_id?: string | undefined;
  delivery_mode?: UpdateSubscriptionDeliveryMode | undefined;
  endpoint_id?: string | undefined;
  filter_config?: FilterConfiguration | undefined;
  function?: string | undefined;
  name?: string | undefined;
  rate_limit_config?: RateLimitConfiguration | undefined;
  retry_config?: RetryConfiguration | undefined;
  source_id?: string | undefined;
};

export const UpdateSubscription$zodSchema: z.ZodType<UpdateSubscription> = z
  .object({
    alert_config: AlertConfiguration$zodSchema.optional(),
    app_id: z.string().optional(),
    delivery_mode: UpdateSubscriptionDeliveryMode$zodSchema.optional(),
    endpoint_id: z.string().optional(),
    filter_config: FilterConfiguration$zodSchema.optional(),
    function: z.string().optional(),
    name: z.string().optional(),
    rate_limit_config: RateLimitConfiguration$zodSchema.optional(),
    retry_config: RetryConfiguration$zodSchema.optional(),
    source_id: z.string().optional(),
  });
