/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PubSubConfig, PubSubConfig$zodSchema } from "./pubsubconfig.js";
import { SourceType, SourceType$zodSchema } from "./sourcetype.js";
import {
  UpdateCustomResponse,
  UpdateCustomResponse$zodSchema,
} from "./updatecustomresponse.js";
import { VerifierConfig, VerifierConfig$zodSchema } from "./verifierconfig.js";

export type UpdateSource = {
  body_function?: string | undefined;
  custom_response?: UpdateCustomResponse | undefined;
  forward_headers?: Array<string> | undefined;
  header_function?: string | undefined;
  idempotency_keys?: Array<string> | undefined;
  is_disabled?: boolean | undefined;
  name?: string | undefined;
  pub_sub?: PubSubConfig | undefined;
  type?: SourceType | undefined;
  verifier?: VerifierConfig | undefined;
};

export const UpdateSource$zodSchema: z.ZodType<UpdateSource> = z.object({
  body_function: z.string().optional().describe(
    "Function is a javascript function used to mutate the payload\nimmediately after ingesting an event",
  ),
  custom_response: UpdateCustomResponse$zodSchema.optional().describe(
    "Custom response is used to define a custom response for incoming\nwebhooks project sources only.",
  ),
  forward_headers: z.array(z.string()).optional().describe(
    "Soecfy header you want convoy to save from the ingest request and forward to your endpoints when the event is dispatched.",
  ),
  header_function: z.string().optional().describe(
    "Function is a javascript function used to mutate the headers\nimmediately after ingesting an event",
  ),
  idempotency_keys: z.array(z.string()).optional().describe(
    "IdempotencyKeys are used to specify parts of a webhook request to uniquely\nidentify the event in an incoming webhooks project.",
  ),
  is_disabled: z.boolean().optional().describe(
    "This is used to manually enable/disable the source.",
  ),
  name: z.string().optional().describe("Source name."),
  pub_sub: PubSubConfig$zodSchema.optional().describe(
    "PubSub are used to specify message broker sources for outgoing\nwebhooks projects, you only need to specify this when the source type is `pub_sub`.",
  ),
  type: SourceType$zodSchema.optional().describe("Source Type."),
  verifier: VerifierConfig$zodSchema.optional().describe(
    "Verifiers are used to verify webhook events ingested in incoming\nwebhooks projects.  If set, type is required and match the verifier\ntype object you choose.",
  ),
});
