/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointResponse,
  EndpointResponse$zodSchema,
} from "./endpointresponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import { UpdateEndpoint, UpdateEndpoint$zodSchema } from "./updateendpoint.js";

export type UpdateEndpointRequest = {
  projectID: string;
  endpointID: string;
  UpdateEndpoint: UpdateEndpoint;
};

export const UpdateEndpointRequest$zodSchema: z.ZodType<UpdateEndpointRequest> =
  z.object({
    UpdateEndpoint: UpdateEndpoint$zodSchema.describe("Endpoint Details"),
    endpointID: z.string().describe("Endpoint ID"),
    projectID: z.string().describe("Project ID"),
  });

/**
 * Not Found
 */
export type UpdateEndpointNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEndpointNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateEndpointNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdateEndpointUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEndpointUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdateEndpointUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdateEndpointBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEndpointBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateEndpointBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Accepted
 */
export type UpdateEndpointResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EndpointResponse | undefined;
};

export const UpdateEndpointResponseBody$zodSchema: z.ZodType<
  UpdateEndpointResponseBody
> = z.object({
  data: EndpointResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Accepted");

export type UpdateEndpointResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndTwoApplicationJsonObject?:
    | UpdateEndpointResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | UpdateEndpointBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdateEndpointUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdateEndpointNotFoundResponseBody
    | undefined;
};

export const UpdateEndpointResponse$zodSchema: z.ZodType<
  UpdateEndpointResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    UpdateEndpointNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    UpdateEndpointUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    UpdateEndpointBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndTwoApplicationJsonObject: z.lazy(() =>
    UpdateEndpointResponseBody$zodSchema
  ).optional().describe("Accepted"),
});
