/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EndpointAuthentication,
  EndpointAuthentication$zodSchema,
} from "./endpointauthentication.js";

export type UpdateEndpoint = {
  advanced_signatures?: boolean | undefined;
  authentication?: EndpointAuthentication | undefined;
  description?: string | undefined;
  http_timeout?: number | undefined;
  is_disabled?: boolean | undefined;
  name?: string | undefined;
  owner_id?: string | undefined;
  rate_limit?: number | undefined;
  rate_limit_duration?: number | undefined;
  secret?: string | undefined;
  slack_webhook_url?: string | undefined;
  support_email?: string | undefined;
  url?: string | undefined;
};

export const UpdateEndpoint$zodSchema: z.ZodType<UpdateEndpoint> = z.object({
  advanced_signatures: z.boolean().optional(),
  authentication: EndpointAuthentication$zodSchema.optional(),
  description: z.string().optional(),
  http_timeout: z.int().optional(),
  is_disabled: z.boolean().optional(),
  name: z.string().optional(),
  owner_id: z.string().optional(),
  rate_limit: z.int().optional(),
  rate_limit_duration: z.int().optional(),
  secret: z.string().optional(),
  slack_webhook_url: z.string().optional(),
  support_email: z.string().optional(),
  url: z.string().optional(),
});
