/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EventTypeResponse,
  EventTypeResponse$zodSchema,
} from "./eventtyperesponse.js";
import { ObjectT, ObjectT$zodSchema } from "./object.js";
import {
  UpdateEventType,
  UpdateEventType$zodSchema,
} from "./updateeventtype.js";

export type UpdateEventTypeRequest = {
  projectID: string;
  eventTypeID: string;
  UpdateEventType: UpdateEventType;
};

export const UpdateEventTypeRequest$zodSchema: z.ZodType<
  UpdateEventTypeRequest
> = z.object({
  UpdateEventType: UpdateEventType$zodSchema.describe("Event Type Details"),
  eventTypeID: z.string().describe("Event Type ID"),
  projectID: z.string().describe("Project ID"),
});

/**
 * Not Found
 */
export type UpdateEventTypeNotFoundResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEventTypeNotFoundResponseBody$zodSchema: z.ZodType<
  UpdateEventTypeNotFoundResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Not Found");

/**
 * Unauthorized
 */
export type UpdateEventTypeUnauthorizedResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEventTypeUnauthorizedResponseBody$zodSchema: z.ZodType<
  UpdateEventTypeUnauthorizedResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Unauthorized");

/**
 * Bad Request
 */
export type UpdateEventTypeBadRequestResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: ObjectT | undefined;
};

export const UpdateEventTypeBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateEventTypeBadRequestResponseBody
> = z.object({
  data: ObjectT$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Bad Request");

/**
 * Created
 */
export type UpdateEventTypeResponseBody = {
  message?: string | undefined;
  status?: boolean | undefined;
  data?: EventTypeResponse | undefined;
};

export const UpdateEventTypeResponseBody$zodSchema: z.ZodType<
  UpdateEventTypeResponseBody
> = z.object({
  data: EventTypeResponse$zodSchema.optional(),
  message: z.string().optional(),
  status: z.boolean().optional(),
}).describe("Created");

export type UpdateEventTypeResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  twoHundredAndOneApplicationJsonObject?:
    | UpdateEventTypeResponseBody
    | undefined;
  fourHundredApplicationJsonObject?:
    | UpdateEventTypeBadRequestResponseBody
    | undefined;
  fourHundredAndOneApplicationJsonObject?:
    | UpdateEventTypeUnauthorizedResponseBody
    | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | UpdateEventTypeNotFoundResponseBody
    | undefined;
};

export const UpdateEventTypeResponse$zodSchema: z.ZodType<
  UpdateEventTypeResponse
> = z.object({
  ContentType: z.string().describe(
    "HTTP response content type for this operation",
  ),
  RawResponse: z.custom<Response>(x => x instanceof Response).describe(
    "Raw HTTP response; suitable for custom response parsing",
  ),
  StatusCode: z.int().describe("HTTP response status code for this operation"),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    UpdateEventTypeNotFoundResponseBody$zodSchema
  ).optional().describe("Not Found"),
  fourHundredAndOneApplicationJsonObject: z.lazy(() =>
    UpdateEventTypeUnauthorizedResponseBody$zodSchema
  ).optional().describe("Unauthorized"),
  fourHundredApplicationJsonObject: z.lazy(() =>
    UpdateEventTypeBadRequestResponseBody$zodSchema
  ).optional().describe("Bad Request"),
  twoHundredAndOneApplicationJsonObject: z.lazy(() =>
    UpdateEventTypeResponseBody$zodSchema
  ).optional().describe("Created"),
});
