/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const VerifierType = {
  Noop: "noop",
  Hmac: "hmac",
  BasicAuth: "basic_auth",
  ApiKey: "api_key",
} as const;
export type VerifierType = ClosedEnum<typeof VerifierType>;

export const VerifierType$zodSchema = z.enum([
  "noop",
  "hmac",
  "basic_auth",
  "api_key",
]);
