/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";
import { BasicAuth, BasicAuth$zodSchema } from "./basicauth.js";
import { HMac, HMac$zodSchema } from "./hmac.js";
import { VerifierType, VerifierType$zodSchema } from "./verifiertype.js";

export type VerifierConfig = {
  api_key?: ApiKey | undefined;
  basic_auth?: BasicAuth | undefined;
  hmac?: HMac | undefined;
  type: VerifierType;
};

export const VerifierConfig$zodSchema: z.ZodType<VerifierConfig> = z.object({
  api_key: ApiKey$zodSchema.optional(),
  basic_auth: BasicAuth$zodSchema.optional(),
  hmac: HMac$zodSchema.optional(),
  type: VerifierType$zodSchema,
});
